import type { Locale } from "@/lib/i18n";

export const websiteCheckTranslations = {
  de: {
    nav: { check: "Website-Check", scope: "Prüfumfang", faq: "FAQ", consulting: "Beratung" },
    hero: {
      confirmed: "Ihre E-Mail-Adresse wurde bestätigt. Vielen Dank.",
      invalid: "Der Bestätigungslink ist ungültig oder abgelaufen. Eine Aufnahme in den Verteiler ist nicht erfolgt.",
      title: "Wie gut arbeitet Ihre Website wirklich?",
      text: "Analysieren Sie kostenlos die Performance, Suchmaschinen-Basis, Barrierefreiheit und technische Qualität Ihrer Website – verständlich ausgewertet und klar erklärt.",
      trust: ["Kostenloser Basis-Check", "Ergebnis in wenigen Minuten", "Keine Zugangsdaten erforderlich", "Nur öffentlich erreichbare Seiten"],
      trustLabel: "Vorteile des Website-Checks",
    },
    scope: {
      eyebrow: "Was wird geprüft?",
      title: "Technische Qualität, verständlich auf das Geschäft übersetzt.",
      cards: [
        ["Performance", "Wir prüfen, wie schnell wichtige Inhalte sichtbar und Seiten bedienbar werden."],
        ["SEO-Grundlagen", "Technische Grundlagen für eine verständliche Darstellung in Suchmaschinen werden ausgewertet."],
        ["Barrierefreiheit", "Der Check erkennt ausgewählte Hürden für Tastatur-, Screenreader- und kontrastbewusste Nutzung."],
        ["Technische Qualität", "Best Practices, Stabilität und auffällige Ressourcen werden in einen geschäftlichen Kontext übersetzt."],
      ],
    },
    importance: {
      eyebrow: "Warum ist das wichtig?",
      title: "Eine Website ist ein geschäftlicher Kontaktpunkt – nicht nur eine technische Datei.",
      items: [
        ["Geringere Absprungrisiken", "Schnell sichtbare und stabil bedienbare Inhalte können verhindern, dass Interessenten den ersten Eindruck vorzeitig abbrechen."],
        ["Bessere mobile Nutzererfahrung", "Viele geschäftliche Erstkontakte beginnen auf dem Smartphone. Eine belastbare mobile Basis erleichtert Orientierung und Kontaktaufnahme."],
        ["Professionellerer Eindruck", "Stabile Layouts, klare Bedienung und saubere technische Grundlagen unterstützen einen verlässlichen Markenauftritt."],
        ["Technische Voraussetzungen für Sichtbarkeit", "Saubere SEO-Grundlagen helfen Suchmaschinen, Inhalte technisch zu erfassen. Ein hoher Score allein garantiert jedoch weder Rankings noch Umsatz."],
        ["Zugänglichere Inhalte", "Bessere Kontraste, Alternativtexte und nachvollziehbare Bedienelemente können mehr Menschen den Zugang zu Ihren Angeboten ermöglichen."],
      ],
    },
    faq: {
      eyebrow: "Häufige Fragen",
      title: "Transparent erklärt.",
      cta: "Unverbindliches Erstgespräch vereinbaren",
      items: [
        ["Ist der Website-Check wirklich kostenlos?", "Ja. Der Basis-Report mit vier Scores, zentralen Kennzahlen und den wichtigsten Erkenntnissen ist kostenlos und ohne Eingabe von Kontaktdaten sichtbar."],
        ["Welche Daten werden geprüft?", "Die öffentlich erreichbare URL wird auf Performance, Barrierefreiheit, Best Practices und technische SEO-Grundlagen geprüft. Zugangsdaten oder interne Inhalte werden nicht abgefragt."],
        ["Werden Änderungen an meiner Website vorgenommen?", "Nein. Der Check liest ausschließlich öffentlich verfügbare Messdaten aus und nimmt keinerlei Änderungen an Ihrer Website vor."],
        ["Brauchen Sie Zugangsdaten?", "Nein. Für den Website-Check werden weder CMS-, Hosting- noch Analyse-Zugangsdaten benötigt."],
        ["Warum können die Werte schwanken?", "Messwerte können sich durch Serverauslastung, Netzwerkbedingungen, Drittanbieter-Skripte, neue Inhalte oder den Testzeitpunkt verändern. Einzelne Messungen sind daher Momentaufnahmen."],
        ["Ist der Check mit Google PageSpeed Insights identisch?", "Die technische Datenquelle umfasst PageSpeed Insights. Die Ergebnisse werden zusätzlich priorisiert und in verständliche mögliche Auswirkungen für Unternehmen übersetzt."],
        ["Was passiert mit meinen Kontaktdaten?", "Kontaktdaten werden nur verarbeitet, wenn Sie den ausführlichen Report anfordern. Sie dienen der Report-Zustellung und werden entsprechend der Datenschutzerklärung behandelt."],
        ["Bekomme ich automatisch einen Newsletter?", "Nein. Marketing-E-Mails sind optional und die Checkbox ist nicht vorausgewählt. Eine Aufnahme erfolgt erst nach separater Double-Opt-in-Bestätigung."],
      ],
    },
    footer: { imprint: "Impressum", privacy: "Datenschutz", terms: "AGB", cookies: "Cookie-Richtlinie" },
    tool: {
      report: "Kostenloser Website-Report", resultFor: "Ihr Ergebnis für", test: "Test", analysis: "Analyse",
      urlLabel: "Website-URL", placeholder: "beispiel.de", running: "Analyse läuft …", submit: "Website vollständig analysieren",
      help: "Mit oder ohne https:// – geprüft werden ausschließlich öffentlich erreichbare Informationen.", device: "Testgerät auswählen",
      invalidUrl: "Bitte geben Sie eine gültige Website-Adresse ein.", genericError: "Die Analyse konnte gerade nicht abgeschlossen werden.",
      idleTitle: "19 Analysebereiche, ein vollständiger Überblick", idleText: "Prüfen Sie Performance, CMS, Hosting-Indikatoren, DNS, SSL, Tracking, Sicherheit, SEO, AEO, GEO, Barrierefreiheit, Rechtliches und weitere öffentlich sichtbare Signale.",
      errorTitle: "Die Analyse konnte nicht abgeschlossen werden", errorHint: "Prüfen Sie die Adresse und starten Sie den Check erneut.",
      metricsEyebrow: "Zentrale Kennzahlen", metricsTitle: "Was Besucher beim Laden erleben",
      fieldData: "Für einzelne Kennzahlen sind reale Felddaten verfügbar. Andere Werte stammen aus einer standardisierten Labormessung.",
      noFieldData: "Für diese URL liegen keine ausreichenden realen Felddaten vor. Die angezeigten Werte stammen aus einer standardisierten Labormessung.",
      unavailable: "Nicht verfügbar", ratingGood: "Der Messwert liegt im empfohlenen Bereich.", ratingImprove: "Der Messwert zeigt konkretes Verbesserungspotenzial.", ratingPoor: "Der Messwert sollte priorisiert geprüft werden.", ratingUnknown: "Für diese Kennzahl wurde kein verwertbarer Wert geliefert.",
      findingsEyebrow: "Verständliche Einordnung", findingsTitle: "Die wichtigsten Erkenntnisse für Ihr Unternehmen",
      progressTitle: "Ihre Website wird vollständig analysiert", progressText: "Die erweiterte Prüfung kann je nach Website und DNS-Antwort einige Sekunden dauern.",
      progress: ["Website wird auf Erreichbarkeit geprüft", "Performance und technische Auslieferung werden analysiert", "CMS, Frameworks und Hosting-Indikatoren werden erkannt", "DNS, SSL und Sicherheits-Header werden geprüft", "SEO, AEO und GEO werden ausgewertet", "Tracking, Cookies, Formulare und Rechtliches werden untersucht", "Alle 19 Analysebereiche werden aufbereitet"],
    },
  },
  en: {
    nav: { check: "Website check", scope: "What we check", faq: "FAQ", consulting: "Consulting" },
    hero: { confirmed: "Your email address has been confirmed. Thank you.", invalid: "The confirmation link is invalid or has expired. You have not been added to the mailing list.", title: "How well does your website really perform?", text: "Analyse your website's performance, SEO foundations, accessibility and technical quality for free – clearly evaluated and explained.", trust: ["Free basic check", "Results in a few minutes", "No login details required", "Publicly accessible pages only"], trustLabel: "Benefits of the website check" },
    scope: { eyebrow: "What do we check?", title: "Technical quality translated into clear business relevance.", cards: [["Performance", "We assess how quickly important content appears and the page becomes usable."], ["SEO foundations", "Technical foundations that help search engines understand and present your website are evaluated."], ["Accessibility", "The check identifies selected barriers affecting keyboard, screen-reader and contrast-conscious use."], ["Technical quality", "Best practices, stability and notable resources are translated into business context."]] },
    importance: { eyebrow: "Why does it matter?", title: "A website is a business touchpoint – not just a technical file.", items: [["Lower bounce risk", "Fast, visible and stable content can keep prospects from leaving before they understand your offer."], ["Better mobile experience", "Many first business interactions start on a smartphone. A solid mobile foundation makes orientation and contact easier."], ["More professional impression", "Stable layouts, clear interaction and clean technical foundations support a reliable brand presence."], ["Technical foundations for visibility", "Clean SEO foundations help search engines process content. A high score alone does not guarantee rankings or revenue."], ["More accessible content", "Better contrast, alternative text and understandable controls can make your offer accessible to more people."]] },
    faq: { eyebrow: "Frequently asked questions", title: "Explained transparently.", cta: "Book a non-binding initial consultation", items: [["Is the website check really free?", "Yes. The basic report with four scores, key metrics and the most important findings is free and visible without contact details."], ["What data is checked?", "The publicly accessible URL is tested for performance, accessibility, best practices and technical SEO foundations. No credentials or internal content are requested."], ["Will any changes be made to my website?", "No. The check only reads publicly available measurement data and makes no changes to your website."], ["Do you need login details?", "No. CMS, hosting and analytics credentials are not required."], ["Why can the scores fluctuate?", "Measurements can change due to server load, network conditions, third-party scripts, new content or the test time. Each test is a snapshot."], ["Is this identical to Google PageSpeed Insights?", "PageSpeed Insights is part of the technical data source. Results are additionally prioritised and translated into understandable business implications."], ["What happens to my contact details?", "Contact details are only processed when you request the detailed report. They are used to deliver it and handled according to the privacy policy."], ["Will I automatically receive a newsletter?", "No. Marketing emails are optional and the checkbox is not preselected. Subscription only occurs after a separate double opt-in confirmation."]] },
    footer: { imprint: "Legal notice", privacy: "Privacy", terms: "Terms", cookies: "Cookie policy" },
    tool: { report: "Free website report", resultFor: "Your result for", test: "Test", analysis: "Analysis", urlLabel: "Website URL", placeholder: "example.com", running: "Analysing …", submit: "Analyse website completely", help: "With or without https:// – only publicly accessible information is checked.", device: "Select test device", invalidUrl: "Please enter a valid website address.", genericError: "The analysis could not be completed right now.", idleTitle: "19 analysis areas, one complete overview", idleText: "Check performance, CMS, hosting indicators, DNS, SSL, tracking, security, SEO, AEO, GEO, accessibility, legal signals and more.", errorTitle: "The analysis could not be completed", errorHint: "Check the address and start the analysis again.", metricsEyebrow: "Key metrics", metricsTitle: "What visitors experience while loading", fieldData: "Real-world field data is available for some metrics. Other values come from a standardised lab test.", noFieldData: "There is not enough real-world field data for this URL. The displayed values come from a standardised lab test.", unavailable: "Not available", ratingGood: "The metric is within the recommended range.", ratingImprove: "The metric shows clear room for improvement.", ratingPoor: "This metric should be reviewed as a priority.", ratingUnknown: "No usable value was returned for this metric.", findingsEyebrow: "Clear interpretation", findingsTitle: "The most important findings for your business", progressTitle: "Your website is being fully analysed", progressText: "The extended check may take a few seconds depending on the website and DNS response.", progress: ["Checking website availability", "Analysing performance and technical delivery", "Detecting CMS, frameworks and hosting indicators", "Checking DNS, SSL and security headers", "Evaluating SEO, AEO and GEO", "Inspecting tracking, cookies, forms and legal signals", "Preparing all 19 analysis areas"] },
  },
  sq: {
    nav: { check: "Kontrolli i faqes", scope: "Çfarë kontrollohet", faq: "FAQ", consulting: "Këshillim" },
    hero: { confirmed: "Adresa juaj e emailit u konfirmua. Faleminderit.", invalid: "Lidhja e konfirmimit është e pavlefshme ose ka skaduar. Nuk jeni shtuar në listën e emailit.", title: "Sa mirë funksionon vërtet faqja juaj?", text: "Analizoni falas performancën, bazat e SEO-së, aksesueshmërinë dhe cilësinë teknike të faqes suaj – me shpjegime të qarta.", trust: ["Kontroll bazë falas", "Rezultat brenda pak minutash", "Nuk kërkohen të dhëna hyrjeje", "Vetëm faqe publike"], trustLabel: "Përfitimet e kontrollit" },
    scope: { eyebrow: "Çfarë kontrollohet?", title: "Cilësia teknike e përkthyer në rëndësi të kuptueshme për biznesin.", cards: [["Performanca", "Kontrollojmë sa shpejt shfaqet përmbajtja kryesore dhe faqja bëhet e përdorshme."], ["Bazat e SEO-së", "Vlerësohen bazat teknike që ndihmojnë motorët e kërkimit ta kuptojnë faqen."], ["Aksesueshmëria", "Kontrolli identifikon pengesa të zgjedhura për tastierën, lexuesit e ekranit dhe kontrastin."], ["Cilësia teknike", "Praktikat e mira, stabiliteti dhe burimet e dukshme vendosen në kontekst biznesi."]] },
    importance: { eyebrow: "Pse është e rëndësishme?", title: "Faqja është një pikë kontakti biznesi – jo vetëm një skedar teknik.", items: [["Rrezik më i ulët largimi", "Përmbajtja e shpejtë dhe e qëndrueshme mund të pengojë vizitorët të largohen para kohe."], ["Përvojë më e mirë mobile", "Shumë kontakte të para fillojnë në telefon. Një bazë e fortë mobile e lehtëson orientimin dhe kontaktin."], ["Përshtypje më profesionale", "Paraqitja stabile, përdorimi i qartë dhe bazat e pastra teknike mbështesin markën."], ["Baza teknike për dukshmëri", "Bazat e mira të SEO-së ndihmojnë motorët e kërkimit. Një rezultat i lartë nuk garanton renditje ose të ardhura."], ["Përmbajtje më e aksesueshme", "Kontrasti, tekstet alternative dhe kontrollet e kuptueshme mund ta bëjnë ofertën të arritshme për më shumë njerëz."]] },
    faq: { eyebrow: "Pyetje të shpeshta", title: "Shpjeguar me transparencë.", cta: "Rezervoni një bisedë fillestare pa detyrim", items: [["A është kontrolli vërtet falas?", "Po. Raporti bazë me katër rezultate, metrika kryesore dhe gjetjet më të rëndësishme është falas dhe i dukshëm pa të dhëna kontakti."], ["Cilat të dhëna kontrollohen?", "URL-ja publike testohet për performancë, aksesueshmëri, praktika të mira dhe baza teknike të SEO-së. Nuk kërkohen kredenciale ose përmbajtje të brendshme."], ["A bëhen ndryshime në faqen time?", "Jo. Kontrolli lexon vetëm të dhëna publike dhe nuk bën asnjë ndryshim."], ["A nevojiten të dhëna hyrjeje?", "Jo. Nuk nevojiten të dhëna për CMS, hosting ose analiza."], ["Pse rezultatet mund të ndryshojnë?", "Matjet mund të ndryshojnë nga ngarkesa e serverit, rrjeti, skriptet e palëve të treta, përmbajtja e re ose koha e testit."], ["A është identik me Google PageSpeed Insights?", "PageSpeed Insights është pjesë e burimit teknik. Rezultatet gjithashtu prioritizohen dhe shpjegohen në kontekst biznesi."], ["Çfarë ndodh me të dhënat e kontaktit?", "Të dhënat përpunohen vetëm kur kërkoni raportin e detajuar dhe trajtohen sipas politikës së privatësisë."], ["A marr automatikisht newsletter?", "Jo. Email-et marketing janë opsionale dhe kutia nuk është e zgjedhur paraprakisht. Regjistrimi bëhet vetëm pas konfirmimit double opt-in."]] },
    footer: { imprint: "Impressum", privacy: "Privatësia", terms: "Kushtet", cookies: "Politika e cookies" },
    tool: { report: "Raport falas i faqes", resultFor: "Rezultati juaj për", test: "Testi", analysis: "Analiza", urlLabel: "URL-ja e faqes", placeholder: "shembull.com", running: "Duke analizuar …", submit: "Analizoni plotësisht faqen", help: "Me ose pa https:// – kontrollohen vetëm informacionet publike.", device: "Zgjidhni pajisjen e testit", invalidUrl: "Ju lutemi vendosni një adresë të vlefshme.", genericError: "Analiza nuk mund të përfundohej tani.", idleTitle: "19 fusha analize, një pamje e plotë", idleText: "Kontrolloni performancën, CMS, hosting, DNS, SSL, tracking, sigurinë, SEO, AEO, GEO, aksesueshmërinë dhe sinjale të tjera publike.", errorTitle: "Analiza nuk mund të përfundohej", errorHint: "Kontrolloni adresën dhe niseni përsëri.", metricsEyebrow: "Metrikat kryesore", metricsTitle: "Çfarë përjetojnë vizitorët gjatë ngarkimit", fieldData: "Për disa metrika ka të dhëna reale. Vlerat e tjera vijnë nga një test laboratorik i standardizuar.", noFieldData: "Nuk ka të dhëna reale të mjaftueshme për këtë URL. Vlerat vijnë nga një test laboratorik.", unavailable: "Nuk disponohet", ratingGood: "Metrika është brenda kufirit të rekomanduar.", ratingImprove: "Metrika tregon hapësirë të qartë për përmirësim.", ratingPoor: "Kjo metrikë duhet kontrolluar me përparësi.", ratingUnknown: "Nuk u kthye një vlerë e përdorshme.", findingsEyebrow: "Shpjegim i qartë", findingsTitle: "Gjetjet më të rëndësishme për biznesin tuaj", progressTitle: "Faqja juaj po analizohet plotësisht", progressText: "Kontrolli i zgjeruar mund të zgjasë disa sekonda, varësisht nga faqja dhe DNS.", progress: ["Po kontrollohet aksesueshmëria e faqes", "Po analizohet performanca dhe shpërndarja teknike", "Po zbulohen CMS, framework-et dhe hosting-u", "Po kontrollohen DNS, SSL dhe header-at e sigurisë", "Po vlerësohen SEO, AEO dhe GEO", "Po kontrollohen tracking, cookies, formularët dhe aspektet ligjore", "Po përgatiten të 19 fushat e analizës"] },
  },
} as const;

export function getWebsiteCheckTranslation(locale: Locale) {
  return websiteCheckTranslations[locale];
}
