import type { Locale } from "@/lib/i18n";
import type { ServicePageCopy } from "./types";

export const cloudAppCareCopy = {
  de: {
    seoTitle: "Server-Wartung, Docker & Backup in München | Cloud & App Care",
    seoDescription: "Linux-Server und Docker-Anwendungen betreuen lassen: Cloud & App Care für KMU in München und Umgebung. Ab 499 € netto monatlich mit vereinbartem Backup-Umfang.",
    eyebrow: "Cloud & App Care · Server und Unternehmens-Apps",
    heading: "Server, Docker-Anwendungen und Backups betreuen lassen.",
    intro: "Ein eingerichteter Server braucht auch danach Aufmerksamkeit. Ich betreue Linux-Server, Docker-Anwendungen und passende Open-Source-Lösungen für Unternehmen in München und 50 km Umland. Von Fürstenfeldbruck aus unterstütze ich Sie bei der laufenden Pflege, vereinbarten Änderungen und der Prüfung Ihrer Datensicherung.",
    problemsTitle: "Kommt Ihnen das bekannt vor?",
    problems: [
      "Eine wichtige Anwendung läuft auf einem Server, aber Updates und Zuständigkeiten sind ungeklärt.",
      "Sicherungen sind eingerichtet, doch niemand prüft regelmäßig Ergebnisse oder testet eine Wiederherstellung.",
      "Für kleine Anpassungen fehlt intern die Zeit oder das Wissen über die vorhandene Umgebung.",
    ],
    benefitsTitle: "Ein klarer Rahmen für den laufenden Betrieb",
    benefits: [
      { title: "Regelmäßige technische Pflege", text: "Vereinbarte monatliche Wartung verbindet Updates mit Kompatibilitätsprüfung und Funktionstests. Auffälligkeiten und erledigte Arbeiten werden dokumentiert." },
      { title: "Sicherungen mit Rückmeldung", text: "Wöchentliche Ergebnisprüfungen und quartalsweise stichprobenartige Wiederherstellungen machen erkennbar, ob die vereinbarte Sicherung wie vorgesehen funktioniert." },
      { title: "Planbare Zusammenarbeit", text: "Sie haben einen Ansprechpartner und ein vereinbartes Zeitbudget. Zusätzlichen Aufwand stimmen wir vor Beginn ab, damit Aufgaben und Kosten nachvollziehbar bleiben." },
    ],
    deliverablesTitle: "Was Cloud & App Care umfasst",
    deliverables: [
      { title: "Ein überschaubarer Referenzumfang", text: "Ab 499 € netto monatlich betreue ich einen Linux-Server und einen produktiven Anwendungsstack einschließlich vereinbarter Abhängigkeiten. Vier Stunden gesamte Servicezeit pro Monat sind enthalten." },
      { title: "Server- und Anwendungspflege", text: "Monatliche Pflege und Funktionstests stehen im Mittelpunkt. Kleine Konfigurationsänderungen sind im verbleibenden Zeitbudget möglich; Wartung, Support, Abstimmung und Dokumentation teilen sich dieses Budget." },
      { title: "Vereinbarte Datensicherung", text: "Nach gesondert vereinbarter Einrichtung erfolgen tägliche automatische Sicherungen auf ein externes Backupziel für bis zu 100 GB Quelldaten. Gesicherte Daten und Aufbewahrung legen wir im Angebot fest." },
      { title: "Einrichtung und Erweiterungen", text: "Neue Docker- oder Open-Source-Anwendungen, Migrationen, Backup-Einrichtung und größere Versionswechsel erhalten ein separates Angebot. Hosting, Lizenzen und Backup-Speicher werden zusätzlich ausgewiesen." },
    ],
    processTitle: "Vom vorhandenen System zur laufenden Betreuung",
    process: [
      { title: "Umgebung prüfen", text: "Wir klären Anwendungen, Zugänge, Datenmenge und bisherigen Sicherungsstand. Bestehende Probleme und nötige Vorarbeiten werden vor der Übernahme sichtbar." },
      { title: "Betrieb vereinbaren", text: "Sie erhalten ein Angebot mit betreutem Umfang, Backup-Regeln, Servicefenstern und Reaktionszeiten. Einrichtung oder Migration planen wir bei Bedarf als eigenes Projekt." },
      { title: "Pflegen und dokumentieren", text: "Nach der vereinbarten Übergabe beginnt die Betreuung. Routinepflege hat Vorrang; weitere Aufgaben und zusätzlicher Zeitbedarf werden mit Ihnen abgestimmt." },
    ],
    faqTitle: "Fragen zu Servern, Docker und Backup",
    faqs: [
      { question: "Können Sie meinen bestehenden Server übernehmen?", answer: "Ja, nach einer Prüfung von Zustand, Zugängen und Pflegeaufwand. Der Einstiegspreis setzt eine übernahmefähige Umgebung im beschriebenen Umfang voraus. Größere oder komplexere Systeme erhalten ein angepasstes Angebot." },
      { question: "Ist die Installation einer neuen Anwendung enthalten?", answer: "Neue Installationen und Migrationen sind eigene Projekte. Wir klären Anforderungen und Kosten vorab; anschließend kann Cloud & App Care die vereinbarte laufende Betreuung übernehmen." },
      { question: "Was bedeutet eine getestete Datensicherung?", answer: "Neben wöchentlichen Ergebnisprüfungen erfolgt quartalsweise eine stichprobenartige Wiederherstellung mit dokumentiertem Ergebnis. Ein vollständiger Notfall-Wiederanlauf und verbindliche Wiederherstellungsziele müssen gesondert geplant werden." },
      { question: "Was passiert bei mehr als vier Stunden Aufwand?", answer: "Absehbare Zusatzleistungen werden vorab freigegeben und mit 100 € netto pro Stunde in 15-Minuten-Schritten berechnet. Ungenutzte Servicezeit wird nicht in den Folgemonat übertragen." },
      { question: "Ist bei einer Störung jederzeit jemand erreichbar?", answer: "Servicefenster und Reaktionszeiten werden im Angebot vereinbart. Eine Rufbereitschaft oder 24/7-Betreuung ist im Paket nicht enthalten; notwendige Verfügbarkeit klären wir vor Beginn." },
    ],
    ctaTitle: "Klären wir, welche Betreuung Ihr System braucht.",
    ctaText: "Wählen Sie Cloud & App Care aus und nennen Sie im Kontaktformular Ihre Anwendung, den vorhandenen Server und Ihren Bedarf. Sie erhalten ein auf Ihre Umgebung abgestimmtes Angebot.",
  },
  en: {
    seoTitle: "Server Maintenance, Docker & Backup in Munich | Cloud & App Care",
    seoDescription: "Support for Linux servers and Docker applications: Cloud & App Care for SMEs in Munich and nearby. From €499 net per month with an agreed backup scope.",
    eyebrow: "Cloud & App Care · Servers and business applications",
    heading: "Ongoing care for your servers, Docker applications and backups.",
    intro: "A server needs attention after setup, too. I maintain Linux servers, Docker applications and suitable open-source solutions for businesses in Munich and within 50 km. Based in Fürstenfeldbruck, I help with ongoing maintenance, agreed changes and checks of your data backups.",
    problemsTitle: "Does this sound familiar?",
    problems: [
      "An important application runs on a server, but responsibility for updates is unclear.",
      "Backups are configured, yet nobody regularly reviews the results or tests a restore.",
      "Your team lacks the time or knowledge of the existing environment to make small adjustments.",
    ],
    benefitsTitle: "A clear scope for ongoing operations",
    benefits: [
      { title: "Regular technical maintenance", text: "Agreed monthly maintenance combines updates with compatibility reviews and functional checks. Findings and completed work are documented." },
      { title: "Backups with feedback", text: "Weekly result checks and quarterly sample restores help establish whether the agreed backups work as intended." },
      { title: "Predictable collaboration", text: "You have a dedicated contact and an agreed time allowance. We agree additional work before starting, keeping tasks and costs transparent." },
    ],
    deliverablesTitle: "What Cloud & App Care includes",
    deliverables: [
      { title: "A defined reference scope", text: "From €499 net per month, I support one Linux server and one production application stack, including agreed dependencies. Four hours of total service time per month are included." },
      { title: "Server and application maintenance", text: "Monthly maintenance and functional checks are the priority. Minor configuration changes are possible within the remaining allowance; maintenance, support, coordination and documentation share this time." },
      { title: "Agreed data backups", text: "Following separately agreed setup, automated daily backups run to one external backup target for up to 100 GB of source data. We specify protected data and retention in your quote." },
      { title: "Setup and extensions", text: "New Docker or open-source applications, migrations, backup setup and major version upgrades receive a separate quote. Hosting, licences and backup storage are listed as additional costs." },
    ],
    processTitle: "From your existing system to ongoing support",
    process: [
      { title: "Review the environment", text: "We establish your applications, access, data volume and current backup arrangements. Existing issues and necessary preparation are identified before handover." },
      { title: "Agree the operating scope", text: "Your quote specifies the supported environment, backup rules, service windows and response times. Setup or migration is planned as a separate project where needed." },
      { title: "Maintain and document", text: "Support starts after the agreed handover. Routine maintenance takes priority; further tasks and additional time requirements are discussed with you." },
    ],
    faqTitle: "Questions about servers, Docker and backups",
    faqs: [
      { question: "Can you take over my existing server?", answer: "Yes, after reviewing its condition, access and maintenance needs. The starting price requires a system ready for support within the stated scope. Larger or more complex environments receive an adjusted quote." },
      { question: "Is installing a new application included?", answer: "New installations and migrations are separate projects. We agree requirements and costs in advance; Cloud & App Care can then provide the agreed ongoing support." },
      { question: "What does a tested backup mean?", answer: "Alongside weekly result checks, a sample restore is performed quarterly and its result documented. Full disaster recovery and binding recovery targets need separate planning." },
      { question: "What happens if more than four hours are needed?", answer: "Foreseeable additional work is approved in advance and charged at €100 net per hour in 15-minute increments. Unused service time does not carry over to the following month." },
      { question: "Is support available at any time if something fails?", answer: "Service windows and response times are agreed in your quote. On-call or 24/7 support is not included in the package; we clarify availability requirements before starting." },
    ],
    ctaTitle: "Let’s establish the support your system needs.",
    ctaText: "Select Cloud & App Care and tell me about your application, existing server and requirements in the contact form. You will receive a quote tailored to your environment.",
  },
  sq: {
    seoTitle: "Mirëmbajtje serverësh, Docker dhe backup në Mynih | Cloud & App Care",
    seoDescription: "Mbështetje për serverë Linux dhe aplikacione Docker: Cloud & App Care për NVM në Mynih dhe rrethinë. Nga 499 € neto në muaj me fushë të dakorduar backup-i.",
    eyebrow: "Cloud & App Care · Serverë dhe aplikacione biznesi",
    heading: "Mirëmbajtje për serverët, aplikacionet Docker dhe kopjet rezervë.",
    intro: "Një server ka nevojë për vëmendje edhe pas konfigurimit. Mirëmbaj serverë Linux, aplikacione Docker dhe zgjidhje të përshtatshme me burim të hapur për bizneset në Mynih dhe 50 km përreth. Nga Fürstenfeldbruck ju mbështes me mirëmbajtjen, ndryshimet e dakorduara dhe kontrollin e kopjeve rezervë të të dhënave.",
    problemsTitle: "A ju duken të njohura këto situata?",
    problems: [
      "Një aplikacion i rëndësishëm punon në server, por përgjegjësia për përditësimet është e paqartë.",
      "Backup-et janë konfiguruar, por askush nuk kontrollon rregullisht rezultatet ose teston rikthimin.",
      "Ekipit tuaj i mungon koha ose njohuria për mjedisin ekzistues që të bëjë përshtatje të vogla.",
    ],
    benefitsTitle: "Një fushë e qartë për funksionimin e vazhdueshëm",
    benefits: [
      { title: "Mirëmbajtje teknike e rregullt", text: "Mirëmbajtja mujore e dakorduar bashkon përditësimet me kontrolle përputhshmërie dhe teste funksionale. Gjetjet dhe punët e kryera dokumentohen." },
      { title: "Backup-e me rezultate të kontrolluara", text: "Kontrollet javore dhe rikthimet provë çdo tremujor ndihmojnë të shihet nëse backup-i i dakorduar funksionon siç parashikohet." },
      { title: "Bashkëpunim i planifikueshëm", text: "Keni një person kontakti dhe një buxhet kohor të dakorduar. Punët shtesë dakordohen para fillimit, që detyrat dhe kostot të mbeten transparente." },
    ],
    deliverablesTitle: "Çfarë përfshin Cloud & App Care",
    deliverables: [
      { title: "Një fushë referuese e përcaktuar", text: "Nga 499 € neto në muaj mbështes një server Linux dhe një sistem aplikacioni në prodhim, me varësitë e dakorduara. Përfshihen katër orë kohë totale shërbimi në muaj." },
      { title: "Mirëmbajtje serveri dhe aplikacioni", text: "Mirëmbajtja mujore dhe testet funksionale kanë përparësi. Ndryshime të vogla konfigurimi mund të kryhen brenda kohës së mbetur; mirëmbajtja, mbështetja, koordinimi dhe dokumentimi ndajnë të njëjtin buxhet kohor." },
      { title: "Kopje rezervë të dakorduara", text: "Pas konfigurimit të dakorduar veçmas, kryhen backup-e automatike ditore në një destinacion të jashtëm për deri në 100 GB të dhëna burimore. Të dhënat e mbrojtura dhe afati i ruajtjes përcaktohen në ofertë." },
      { title: "Konfigurim dhe zgjerime", text: "Aplikacionet e reja Docker ose me burim të hapur, migrimet, konfigurimi i backup-it dhe kalimet e mëdha të versioneve ofertohen veçmas. Hostimi, licencat dhe hapësira për backup paraqiten si kosto shtesë." },
    ],
    processTitle: "Nga sistemi ekzistues te mbështetja e vazhdueshme",
    process: [
      { title: "Kontrolli i mjedisit", text: "Sqarojmë aplikacionet, qasjet, vëllimin e të dhënave dhe gjendjen e backup-it. Problemet ekzistuese dhe përgatitjet e nevojshme identifikohen para marrjes në mbështetje." },
      { title: "Dakordimi i funksionimit", text: "Oferta përcakton mjedisin e mbështetur, rregullat e backup-it, oraret e shërbimit dhe kohët e reagimit. Konfigurimi ose migrimi planifikohet si projekt më vete kur nevojitet." },
      { title: "Mirëmbajtja dhe dokumentimi", text: "Mbështetja fillon pas dorëzimit të dakorduar. Mirëmbajtja rutinë ka përparësi; detyrat e tjera dhe koha shtesë dakordohen me ju." },
    ],
    faqTitle: "Pyetje për serverët, Docker dhe backup-in",
    faqs: [
      { question: "A mund të merrni në mbështetje serverin tim ekzistues?", answer: "Po, pas kontrollit të gjendjes, qasjeve dhe nevojave për mirëmbajtje. Çmimi fillestar vlen për një sistem të gatshëm për mbështetje brenda fushës së përshkruar. Mjediset më të mëdha ose më komplekse marrin ofertë të përshtatur." },
      { question: "A përfshihet instalimi i një aplikacioni të ri?", answer: "Instalimet e reja dhe migrimet janë projekte më vete. Kërkesat dhe kostot dakordohen paraprakisht; më pas Cloud & App Care mund të ofrojë mbështetjen e vazhdueshme të dakorduar." },
      { question: "Çfarë do të thotë një backup i testuar?", answer: "Përveç kontrolleve javore të rezultateve, çdo tremujor kryhet një rikthim provë me kampion dhe dokumentohet rezultati. Rikthimi i plotë pas incidentit dhe objektivat detyruese të rikthimit kërkojnë planifikim më vete." },
      { question: "Çfarë ndodh nëse nevojiten më shumë se katër orë?", answer: "Punët shtesë të parashikueshme miratohen paraprakisht dhe faturohen me 100 € neto në orë, në intervale prej 15 minutash. Koha e papërdorur nuk bartet në muajin pasues." },
      { question: "A ofrohet mbështetje në çdo kohë në rast defekti?", answer: "Oraret e shërbimit dhe kohët e reagimit dakordohen në ofertë. Gatishmëria emergjente ose mbështetja 24/7 nuk përfshihen; nevojat për disponueshmëri i sqarojmë para fillimit." },
    ],
    ctaTitle: "Le të sqarojmë çfarë mbështetjeje i duhet sistemit tuaj.",
    ctaText: "Zgjidhni Cloud & App Care dhe përshkruani aplikacionin, serverin ekzistues dhe nevojat tuaja në formularin e kontaktit. Do të merrni një ofertë të përshtatur për mjedisin tuaj.",
  },
} satisfies Record<Locale, ServicePageCopy>;
