import type { Locale } from "@/lib/i18n";
import type { ServicePageCopy } from "./types";

export const individualCareCopy = {
  de: {
    seoTitle: "Individualsoftware & Shopify-Shops in München | Individual Care",
    seoDescription: "Individuelle Software, Schnittstellen, Automatisierungen und Shopify-Shops für KMU in München und Umgebung. Erstellung und Pflege nach Bedarf. Angebot auf Anfrage.",
    eyebrow: "Individual Care · Lösungen nach Ihrem Bedarf",
    heading: "Individualsoftware und Shopify-Shops nach Ihrem Bedarf.",
    intro: "Sie möchten einen Shopify-Shop aufbauen, eine interne Anwendung entwickeln oder wiederkehrende Arbeitsschritte vereinfachen? Mit Individual Care planen wir die passende Lösung für Ihren Betrieb. Ich begleite KMU in München und 50 km Umland von Fürstenfeldbruck aus – bei neuen Projekten ebenso wie bei der Pflege bestehender Lösungen.",
    problemsTitle: "Wo individuelle Unterstützung sinnvoll wird",
    problems: [
      "Informationen werden mehrfach von Hand übertragen, weil vorhandene Systeme nicht miteinander verbunden sind.",
      "Ihr Shop oder Ihre Unternehmenssoftware braucht Funktionen, die eine Standardkonfiguration nicht abdeckt.",
      "Eine bestehende Lösung soll weiterentwickelt und gepflegt werden, aber ein fester technischer Ansprechpartner fehlt.",
    ],
    benefitsTitle: "Vom konkreten Bedarf zur passenden Umsetzung",
    benefits: [
      { title: "Am Arbeitsablauf ausgerichtet", text: "Wir beginnen bei der Aufgabe, die Sie lösen möchten. Daraus ergeben sich Funktionen, Schnittstellen und Prioritäten statt einer langen Wunschliste ohne klaren Nutzen." },
      { title: "Überschaubare Projektschritte", text: "Ein vereinbarter Umfang und nachvollziehbare Zwischenstände helfen Ihnen, Entscheidungen zu treffen. Änderungen und ihre Auswirkungen auf den Aufwand klären wir gemeinsam." },
      { title: "Pflege von Anfang an mitdenken", text: "Schon bei der Planung besprechen wir Betrieb, Zuständigkeiten und spätere Änderungen. Eine laufende Betreuung kann passend zum System vereinbart werden." },
    ],
    deliverablesTitle: "Wobei ich Sie unterstützen kann",
    deliverables: [
      { title: "Individuelle Software", text: "Interne Werkzeuge, Webanwendungen und Erweiterungen für konkrete Geschäftsprozesse: Anforderungen, Umsetzung, Tests und Übergabe werden passend zu Ihrem Vorhaben angeboten." },
      { title: "Schnittstellen und Automatisierungen", text: "Vorhandene Anwendungen lassen sich über geeignete APIs verbinden und wiederkehrende Aufgaben automatisieren. Wir prüfen verfügbare Schnittstellen, Datenflüsse und Fehlerfälle vor der Umsetzung." },
      { title: "Shopify-Shops erstellen und anpassen", text: "Aufbau eines neuen Shops, Anpassungen an bestehenden Shops und vereinbarte Funktionen oder Integrationen. Inhalte, Produktdaten, Designumfang und benötigte Apps legen wir im Projektangebot fest." },
      { title: "Bestehende Lösungen pflegen", text: "Wartung, kleinere Anpassungen und Weiterentwicklung von Shops oder Individualsoftware können separat oder nach einem Projekt vereinbart werden. Umfang und Übernahmefähigkeit prüfen wir zuvor." },
    ],
    processTitle: "So wird aus Ihrer Idee ein konkretes Angebot",
    process: [
      { title: "Vorhaben verstehen", text: "Sie beschreiben Ziel, heutige Abläufe und vorhandene Systeme. Wir klären die wichtigsten Funktionen, Abhängigkeiten und den gewünschten Zeitrahmen." },
      { title: "Umfang und Kosten festlegen", text: "Sie erhalten ein individuelles Angebot mit vereinbarten Ergebnissen und Leistungen. Erstellung, laufende Pflege und Fremdkosten werden nachvollziehbar getrennt." },
      { title: "Umsetzen und übergeben", text: "Die vereinbarte Lösung wird umgesetzt, getestet und übergeben. Bei Bedarf schließen wir eine passende Betreuung oder weitere Entwicklungsschritte an." },
    ],
    faqTitle: "Fragen zu Individualsoftware und Shopify",
    faqs: [
      { question: "Was kostet Individual Care?", answer: "Der Preis richtet sich nach Anforderungen und Umfang und wird auf Anfrage angeboten. Einmaliges Projekt, reine Betreuung oder beides sind möglich. Es gibt keinen pauschalen monatlichen Einstiegspreis für alle individuellen Vorhaben." },
      { question: "Kann ich nur die Pflege meines Shopify-Shops anfragen?", answer: "Ja. Nach einer Prüfung Ihres Shops vereinbaren wir die benötigten Pflegearbeiten und Änderungen. Shopify-Gebühren, kostenpflichtige Themes, Apps und andere Plattformkosten werden gesondert berücksichtigt." },
      { question: "Muss meine Idee bereits vollständig ausgearbeitet sein?", answer: "Nein. Eine Beschreibung des Problems, der beteiligten Personen und Ihrer bestehenden Systeme reicht für die erste Anfrage. Den nötigen Planungs- und Umsetzungsumfang klären wir anschließend gemeinsam." },
      { question: "Können vorhandene Programme miteinander verbunden werden?", answer: "Das hängt von den verfügbaren Schnittstellen, Zugriffsrechten und Datenformaten ab. Ich prüfe die Voraussetzungen und bespreche mit Ihnen, welche Verbindung technisch sinnvoll umsetzbar ist." },
      { question: "Wie werden spätere Änderungen und laufende Kosten geregelt?", answer: "Die Betreuung wird passend zur Lösung vereinbart. Zusatzleistungen außerhalb eines vereinbarten Umfangs erfolgen nach Freigabe für 100 € netto pro Stunde in 15-Minuten-Schritten. Plattformlizenzen, Hosting und weitere Fremdkosten kommen hinzu." },
    ],
    ctaTitle: "Was möchten Sie vereinfachen, aufbauen oder verbessern?",
    ctaText: "Wählen Sie Individual Care und beschreiben Sie Ihr Vorhaben im Kontaktformular. Ob Software, Shopify-Shop oder eine andere individuelle Lösung: Ihre Anfrage ist der Ausgangspunkt für ein passendes Angebot.",
  },
  en: {
    seoTitle: "Custom Software & Shopify Shops in Munich | Individual Care",
    seoDescription: "Custom software, integrations, automation and Shopify shops for SMEs in Munich and nearby. Development and maintenance to suit your needs. Quote on request.",
    eyebrow: "Individual Care · Solutions for your requirements",
    heading: "Custom software and Shopify shops for your business.",
    intro: "Would you like to build a Shopify shop, develop an internal application or simplify recurring tasks? With Individual Care, we plan a solution that suits your business. Based in Fürstenfeldbruck, I support SMEs in Munich and within 50 km with new projects and the maintenance of existing solutions.",
    problemsTitle: "When individual support makes sense",
    problems: [
      "Information is copied by hand several times because existing systems are not connected.",
      "Your shop or business software needs features that a standard configuration cannot provide.",
      "An existing solution needs further development and maintenance, but there is no dedicated technical contact.",
    ],
    benefitsTitle: "From a specific need to a suitable solution",
    benefits: [
      { title: "Designed around your workflow", text: "We start with the task you want to solve. This guides features, integrations and priorities instead of a long wish list without a clear purpose." },
      { title: "Manageable project steps", text: "An agreed scope and clear progress updates help you make decisions. We discuss changes and their effect on the work involved together." },
      { title: "Plan for maintenance early", text: "Operations, responsibilities and future changes are part of the initial planning. Ongoing support can be agreed to suit the system." },
    ],
    deliverablesTitle: "How I can support you",
    deliverables: [
      { title: "Custom software", text: "Internal tools, web applications and extensions for specific business processes: requirements, development, testing and handover are quoted to suit your project." },
      { title: "Integrations and automation", text: "Existing applications can be connected through suitable APIs, and recurring tasks can be automated. We review available interfaces, data flows and failure scenarios before implementation." },
      { title: "Build and customise Shopify shops", text: "A new shop, changes to an existing shop and agreed features or integrations. Content, product data, design scope and required apps are specified in the project quote." },
      { title: "Maintain existing solutions", text: "Maintenance, minor changes and further development of shops or custom software can be agreed separately or after a project. We review the scope and suitability for support first." },
    ],
    processTitle: "How your idea becomes a concrete quote",
    process: [
      { title: "Understand the project", text: "You describe your goal, current workflows and existing systems. We establish the main features, dependencies and desired timeframe." },
      { title: "Agree scope and costs", text: "You receive an individual quote with agreed outcomes and services. Development, ongoing maintenance and third-party costs are clearly separated." },
      { title: "Develop and hand over", text: "The agreed solution is implemented, tested and handed over. Appropriate support or further development can follow where needed." },
    ],
    faqTitle: "Questions about custom software and Shopify",
    faqs: [
      { question: "What does Individual Care cost?", answer: "The price depends on requirements and scope and is quoted on request. A one-off project, support only or both are possible. There is no single monthly starting price for every individual project." },
      { question: "Can I request maintenance for my Shopify shop only?", answer: "Yes. After reviewing your shop, we agree the maintenance work and changes you need. Shopify fees, paid themes, apps and other platform costs are accounted for separately." },
      { question: "Does my idea need to be fully specified already?", answer: "No. A description of the problem, the people involved and your existing systems is enough for an initial enquiry. We then clarify the necessary planning and implementation together." },
      { question: "Can existing programs be connected?", answer: "That depends on the available interfaces, access permissions and data formats. I review the prerequisites and discuss which connection is technically practical for your situation." },
      { question: "How are later changes and ongoing costs handled?", answer: "Support is agreed to suit the solution. Additional work outside an agreed scope requires approval and is charged at €100 net per hour in 15-minute increments. Platform licences, hosting and other third-party costs are additional." },
    ],
    ctaTitle: "What would you like to simplify, build or improve?",
    ctaText: "Select Individual Care and describe your project in the contact form. Whether it is software, a Shopify shop or another individual solution, your enquiry is the starting point for a suitable quote.",
  },
  sq: {
    seoTitle: "Softuer i personalizuar dhe Shopify në Mynih | Individual Care",
    seoDescription: "Softuer i personalizuar, integrime, automatizime dhe dyqane Shopify për NVM në Mynih dhe rrethinë. Zhvillim dhe mirëmbajtje sipas nevojës. Ofertë sipas kërkesës.",
    eyebrow: "Individual Care · Zgjidhje sipas nevojave tuaja",
    heading: "Softuer i personalizuar dhe dyqane Shopify sipas nevojave tuaja.",
    intro: "Dëshironi të ndërtoni një dyqan Shopify, të zhvilloni një aplikacion të brendshëm apo të thjeshtoni punët e përsëritura? Me Individual Care planifikojmë zgjidhjen e përshtatshme për biznesin tuaj. Nga Fürstenfeldbruck mbështes NVM në Mynih dhe 50 km përreth, si për projekte të reja ashtu edhe për mirëmbajtjen e zgjidhjeve ekzistuese.",
    problemsTitle: "Kur nevojitet mbështetje individuale",
    problems: [
      "Informacionet kopjohen disa herë me dorë sepse sistemet ekzistuese nuk janë të lidhura.",
      "Dyqani ose softueri i biznesit tuaj kërkon funksione që konfigurimi standard nuk i mbulon.",
      "Një zgjidhje ekzistuese ka nevojë për zhvillim dhe mirëmbajtje, por mungon një person kontakti teknik i qëndrueshëm.",
    ],
    benefitsTitle: "Nga një nevojë konkrete te zgjidhja e përshtatshme",
    benefits: [
      { title: "I përshtatur me mënyrën tuaj të punës", text: "Nisemi nga detyra që doni të zgjidhni. Prej saj përcaktohen funksionet, integrimet dhe përparësitë, në vend të një liste të gjatë dëshirash pa qëllim të qartë." },
      { title: "Hapa projekti të menaxhueshëm", text: "Një fushë e dakorduar dhe përditësime të qarta mbi ecurinë ju ndihmojnë të merrni vendime. Ndryshimet dhe ndikimin e tyre në punën e nevojshme i diskutojmë së bashku." },
      { title: "Mirëmbajtja planifikohet që në fillim", text: "Funksionimi, përgjegjësitë dhe ndryshimet e ardhshme diskutohen që gjatë planifikimit. Mbështetja e vazhdueshme mund të dakordohet sipas sistemit." },
    ],
    deliverablesTitle: "Si mund t’ju mbështes",
    deliverables: [
      { title: "Softuer i personalizuar", text: "Mjete të brendshme, aplikacione web dhe zgjerime për procese konkrete biznesi: kërkesat, zhvillimi, testimi dhe dorëzimi ofertohen sipas projektit tuaj." },
      { title: "Integrime dhe automatizime", text: "Aplikacionet ekzistuese mund të lidhen përmes API-ve të përshtatshme dhe detyrat e përsëritura mund të automatizohen. Para zbatimit kontrollojmë ndërfaqet, rrjedhën e të dhënave dhe rastet e gabimeve." },
      { title: "Krijim dhe përshtatje dyqanesh Shopify", text: "Ndërtim dyqani të ri, ndryshime në dyqane ekzistuese dhe funksione ose integrime të dakorduara. Përmbajtja, të dhënat e produkteve, fusha e dizajnit dhe aplikacionet e nevojshme përcaktohen në ofertë." },
      { title: "Mirëmbajtje e zgjidhjeve ekzistuese", text: "Mirëmbajtja, ndryshimet e vogla dhe zhvillimi i mëtejshëm i dyqaneve ose softuerit të personalizuar mund të dakordohen veçmas ose pas një projekti. Fillimisht shqyrtojmë fushën dhe përshtatshmërinë për mbështetje." },
    ],
    processTitle: "Si kthehet ideja juaj në një ofertë konkrete",
    process: [
      { title: "Kuptimi i projektit", text: "Përshkruani qëllimin, proceset aktuale dhe sistemet ekzistuese. Sqarojmë funksionet kryesore, varësitë dhe afatin e dëshiruar." },
      { title: "Përcaktimi i fushës dhe kostove", text: "Merrni një ofertë individuale me rezultate dhe shërbime të dakorduara. Zhvillimi, mirëmbajtja e vazhdueshme dhe kostot e palëve të treta paraqiten veçmas." },
      { title: "Zhvillimi dhe dorëzimi", text: "Zgjidhja e dakorduar zbatohet, testohet dhe dorëzohet. Sipas nevojës mund të vazhdojmë me mbështetje të përshtatshme ose hapa të tjerë zhvillimi." },
    ],
    faqTitle: "Pyetje për softuerin e personalizuar dhe Shopify",
    faqs: [
      { question: "Sa kushton Individual Care?", answer: "Çmimi varet nga kërkesat dhe fusha e punës dhe ofrohet sipas kërkesës. Mund të zgjidhni projekt të njëhershëm, vetëm mbështetje ose të dyja. Nuk ka një çmim fillestar mujor të përbashkët për çdo projekt individual." },
      { question: "A mund të kërkoj vetëm mirëmbajtjen e dyqanit tim Shopify?", answer: "Po. Pas shqyrtimit të dyqanit dakordojmë mirëmbajtjen dhe ndryshimet e nevojshme. Tarifat e Shopify, temat me pagesë, aplikacionet dhe kostot e tjera të platformës llogariten veçmas." },
      { question: "A duhet ta kem idenë plotësisht të përgatitur?", answer: "Jo. Për kërkesën e parë mjafton një përshkrim i problemit, personave të përfshirë dhe sistemeve ekzistuese. Më pas sqarojmë së bashku planifikimin dhe zbatimin e nevojshëm." },
      { question: "A mund të lidhen programet ekzistuese me njëri-tjetrin?", answer: "Kjo varet nga ndërfaqet e disponueshme, të drejtat e qasjes dhe formatet e të dhënave. Kontrolloj kushtet dhe diskutojmë se cila lidhje është teknikisht e përshtatshme për ju." },
      { question: "Si rregullohen ndryshimet e mëvonshme dhe kostot e vazhdueshme?", answer: "Mbështetja dakordohet sipas zgjidhjes. Punët shtesë jashtë fushës së dakorduar kryhen pas miratimit me 100 € neto në orë, në intervale prej 15 minutash. Licencat e platformës, hostimi dhe kostot e tjera të palëve të treta janë shtesë." },
    ],
    ctaTitle: "Çfarë dëshironi të thjeshtoni, ndërtoni apo përmirësoni?",
    ctaText: "Zgjidhni Individual Care dhe përshkruani projektin tuaj në formularin e kontaktit. Qoftë softuer, dyqan Shopify apo një zgjidhje tjetër individuale, kërkesa juaj është pika e nisjes për një ofertë të përshtatshme.",
  },
} satisfies Record<Locale, ServicePageCopy>;
