import type { Locale } from "@/lib/i18n";

export const servicesUiCopy = {
  de: {
    home: "Startseite", services: "Leistungen", details: "Leistung im Detail", overview: "Alle Leistungen ansehen",
    eyebrow: "IT-Leistungen für KMU · München und 50 km Umland",
    heading: "Die passende Unterstützung für Ihren nächsten Schritt.",
    intro: "Eine neue Website, digitale Arbeitsplätze, betreute Anwendungen oder eine individuelle Lösung: Hier finden Sie den passenden Einstieg. Auf jeder Leistungsseite erfahren Sie, was wir umsetzen, wie die Betreuung aussieht und welche Kosten Sie einplanen können.",
    viewScope: "Leistungsumfang ansehen", configure: "Paket zusammenstellen", pricing: "Leistungen und Preise",
    pricingTitle: "Einmalig starten. Auf Wunsch laufend betreuen lassen.",
    pricingText: "Wählen Sie die passende Variante. Die Auswahl erscheint anschließend im Kontaktformular – mit getrennten Einmal- und Monatsbeträgen. Dort können Sie Ihre Anforderungen ergänzen.",
    individualPricingTitle: "Ihr Vorhaben bestimmt den Umfang.",
    individualPricingText: "Sie benötigen eine neue Lösung, Unterstützung bei einem bestehenden Projekt oder beides? Wählen Sie Individual Care und beschreiben Sie Ihr Vorhaben. Einmalige Umsetzung und laufende Pflege werden im Angebot getrennt vereinbart.",
    carePricingTitle: "Planbare Betreuung für Ihre Anwendung.",
    carePricingText: "Das monatliche Paket gilt für den beschriebenen Referenzumfang. Einrichtung, Migration und bestehende Probleme klären wir vor der Übernahme und bieten sie gesondert an.",
    conditions: "Zeitbudget, Zusatzleistungen und Zusammenarbeit", related: "Was Ihr Unternehmen außerdem weiterbringt",
    region: "Fürstenfeldbruck · München · 50 km Umland", regionalTitle: "Ein Ansprechpartner für Umsetzung und Betreuung.",
    regionalText: "Leon Pllana IT-Solutions unterstützt kleine und mittlere Unternehmen im Raum München. Die Zusammenarbeit kann remote erfolgen; Vor-Ort-Termine im Einzugsgebiet vereinbaren wir nach Bedarf. Gemeinsam legen wir fest, welche Systeme, Aufgaben und Ziele zum Auftrag gehören.",
    overviewHelp: "Noch nicht sicher, welches Paket passt?", overviewHelpText: "Beschreiben Sie Ihre Ausgangslage. Wir klären gemeinsam, welche Leistungen und welcher Betreuungsumfang für Sie sinnvoll sind.",
    contact: "Vorhaben besprechen", from: "ab", monthly: "/ Monat", once: "einmalig", setupOptional: "Optionaler Start", onRequest: "Auf Anfrage", net: "Alle Preise netto; Fremdkosten separat.",
    summaries: {
      web: "Unternehmenswebsites von der Domain bis zum Go-live – mit optionaler technischer Wartung und Inhaltspflege.",
      workplace: "Microsoft 365, Entra ID und Intune einrichten und betreuen: Benutzer, Geräte und Unternehmens-Apps im vereinbarten Umfang.",
      cloud: "Linux-Server und Docker-Anwendungen pflegen, Sicherungen prüfen und Wiederherstellung stichprobenartig testen.",
      individual: "Individualsoftware, Schnittstellen, Automatisierung und Shopify-Shops: Entwicklung und Pflege nach Ihrem Bedarf.",
    },
  },
  en: {
    home: "Home", services: "Services", details: "Explore this service", overview: "View all services",
    eyebrow: "IT services for SMEs · Munich and within 50 km",
    heading: "The right support for your next step.",
    intro: "A new website, digital workplaces, supported applications or a custom solution: find the right starting point here. Each service page explains what we deliver, how support works and which costs to plan for.",
    viewScope: "Explore the scope", configure: "Configure your package", pricing: "Services and prices",
    pricingTitle: "Start with a project. Add ongoing support if you need it.",
    pricingText: "Choose the option that fits. Your selection appears in the contact form with separate one-off and monthly amounts, where you can add your requirements.",
    individualPricingTitle: "Your project defines the scope.",
    individualPricingText: "Do you need a new solution, help with an existing project or both? Select Individual Care and describe your project. One-off delivery and ongoing maintenance are agreed separately in the quote.",
    carePricingTitle: "Predictable support for your application.",
    carePricingText: "The monthly package covers the reference scope below. Setup, migration and existing issues are assessed before handover and quoted separately.",
    conditions: "Time allowance, additional work and collaboration", related: "Other ways to support your business",
    region: "Fürstenfeldbruck · Munich · within 50 km", regionalTitle: "One contact for delivery and ongoing support.",
    regionalText: "Leon Pllana IT-Solutions supports small and medium-sized businesses in the Munich area. Work can be delivered remotely; on-site appointments within the area are arranged as needed. Together, we agree which systems, tasks and goals the engagement covers.",
    overviewHelp: "Not sure which package fits?", overviewHelpText: "Describe your starting point. Together, we clarify which services and level of support make sense for your business.",
    contact: "Discuss your project", from: "from", monthly: "/ month", once: "one-off", setupOptional: "Optional setup", onRequest: "On request", net: "All prices are net; third-party costs are separate.",
    summaries: {
      web: "Company websites from domain registration to go-live, with optional technical maintenance and content updates.",
      workplace: "Microsoft 365, Entra ID and Intune setup and support: users, devices and business apps within the agreed scope.",
      cloud: "Maintain Linux servers and Docker applications, review backups and carry out sample restore tests.",
      individual: "Custom software, integrations, automation and Shopify shops: development and maintenance for your needs.",
    },
  },
  sq: {
    home: "Faqja kryesore", services: "Shërbimet", details: "Shërbimi në detaje", overview: "Shikoni të gjitha shërbimet",
    eyebrow: "Shërbime IT për NVM · Mynih dhe rrethina deri në 50 km",
    heading: "Mbështetja e duhur për hapin tuaj të ardhshëm.",
    intro: "Një faqe e re web, vende pune digjitale, aplikacione të mirëmbajtura ose zgjidhje individuale: këtu gjeni pikënisjen e duhur. Çdo faqe shërbimi shpjegon çfarë realizojmë, si funksionon mbështetja dhe cilat kosto duhet të planifikoni.",
    viewScope: "Shikoni shërbimet e përfshira", configure: "Përzgjidhni paketën", pricing: "Shërbimet dhe çmimet",
    pricingTitle: "Filloni me një projekt. Shtoni mirëmbajtjen sipas nevojës.",
    pricingText: "Zgjidhni variantin e përshtatshëm. Zgjedhja shfaqet në formularin e kontaktit me shuma të ndara njëherëshe dhe mujore, ku mund të shtoni kërkesat tuaja.",
    individualPricingTitle: "Projekti juaj përcakton shërbimet.",
    individualPricingText: "Ju nevojitet një zgjidhje e re, ndihmë me një projekt ekzistues ose të dyja? Zgjidhni Individual Care dhe përshkruani projektin. Realizimi njëherësh dhe mirëmbajtja periodike dakordohen veçmas në ofertë.",
    carePricingTitle: "Mirëmbajtje e planifikueshme për aplikacionin tuaj.",
    carePricingText: "Paketa mujore mbulon fushën e përshkruar. Konfigurimi, migrimi dhe problemet ekzistuese vlerësohen para marrjes në mirëmbajtje dhe ofertohen veçmas.",
    conditions: "Koha e përfshirë, punët shtesë dhe bashkëpunimi", related: "Shërbime të tjera për biznesin tuaj",
    region: "Fürstenfeldbruck · Mynih · rrethina deri në 50 km", regionalTitle: "Një kontakt për realizimin dhe mirëmbajtjen.",
    regionalText: "Leon Pllana IT-Solutions mbështet ndërmarrjet e vogla dhe të mesme në rajonin e Mynihut. Bashkëpunimi mund të zhvillohet në distancë; takimet në vend dakordohen sipas nevojës. Së bashku përcaktojmë sistemet, detyrat dhe qëllimet e angazhimit.",
    overviewHelp: "Nuk jeni të sigurt cila paketë ju përshtatet?", overviewHelpText: "Përshkruani situatën tuaj. Së bashku sqarojmë shërbimet dhe nivelin e mbështetjes që ka kuptim për biznesin tuaj.",
    contact: "Diskutoni projektin", from: "nga", monthly: "/ muaj", once: "një herë", setupOptional: "Fillim opsional", onRequest: "Me kërkesë", net: "Të gjitha çmimet neto; kostot e palëve të treta veçmas.",
    summaries: {
      web: "Faqe biznesi nga regjistrimi i domenit deri te publikimi, me mirëmbajtje teknike dhe përditësim përmbajtjeje opsional.",
      workplace: "Konfigurim dhe mirëmbajtje e Microsoft 365, Entra ID dhe Intune: përdorues, pajisje dhe aplikacione sipas marrëveshjes.",
      cloud: "Mirëmbajtje serverësh Linux dhe aplikacionesh Docker, kontroll i kopjeve rezervë dhe teste rikthimi me mostra.",
      individual: "Softuer i personalizuar, integrime, automatizim dhe dyqane Shopify: zhvillim dhe mirëmbajtje sipas nevojave tuaja.",
    },
  },
} satisfies Record<Locale, object>;
