import type { Locale } from "@/lib/i18n";

export const servicesUiCopy = {
  de: {
    home: "Startseite", services: "Leistungen", details: "Leistung im Detail", overview: "Alle Leistungen ansehen",
    eyebrow: "IT-Leistungen für KMU · München und 50 km Umland",
    heading: "Die passende Unterstützung für Ihren nächsten Schritt.",
    intro: "Eine neue Website, digitale Arbeitsplätze, betreute Anwendungen oder eine individuelle Lösung: Hier finden Sie den passenden Einstieg. Auf jeder Leistungsseite erfahren Sie, was wir umsetzen, wie die Betreuung aussieht und welche Kosten Sie einplanen können.",
    viewScope: "Leistungsumfang ansehen", configure: "Paket zusammenstellen", pricing: "Leistungen und Preise",
    pricingTitle: "Einmalig sauber starten. Danach verlässlich betreut bleiben.",
    pricingText: "Wählen Sie die passende Variante. Im Mittelpunkt steht, welche Verantwortung wir übernehmen und welcher Zustand dauerhaft sichergestellt werden soll. Einmalige Umsetzung und laufende Betreuung bleiben transparent getrennt.",
    individualPricingTitle: "Ihr Vorhaben bestimmt den Umfang.",
    individualPricingText: "Sie benötigen eine neue Lösung, Unterstützung bei einem bestehenden Projekt oder beides? Wählen Sie Individual Care und beschreiben Sie Ihr Vorhaben. Einmalige Umsetzung und laufende Pflege werden im Angebot getrennt vereinbart.",
    carePricingTitle: "Ein verlässlicher Betriebsrahmen für Ihre Anwendung.",
    carePricingText: "Die monatliche Betreuung deckt den beschriebenen Betriebsrahmen ab. Einrichtung, Migration und bestehende Probleme klären wir vor der Übernahme separat – damit im laufenden Betrieb klar ist, wofür wir Verantwortung übernehmen.",
    conditions: "Rahmenbedingungen & Zusatzleistungen", related: "Was Ihr Unternehmen außerdem weiterbringt",
    region: "Fürstenfeldbruck · München · 50 km Umland", regionalTitle: "Ein Ansprechpartner für Umsetzung und Betreuung.",
    regionalText: "Leon Pllana IT-Solutions unterstützt kleine und mittlere Unternehmen im Raum München. Die Zusammenarbeit kann remote erfolgen; Vor-Ort-Termine im Einzugsgebiet vereinbaren wir nach Bedarf. Gemeinsam legen wir fest, welche Systeme, Aufgaben und Ziele zum Auftrag gehören.",
    overviewHelp: "Noch nicht sicher, welches Paket passt?", overviewHelpText: "Beschreiben Sie Ihre Ausgangslage. Wir klären gemeinsam, welche Leistungen und welcher Betreuungsumfang für Sie sinnvoll sind.",
    contact: "Vorhaben besprechen", from: "ab", monthly: "/ Monat", once: "einmalig", setupOptional: "Optionaler Start", onRequest: "Auf Anfrage", net: "Alle Preise netto; Fremdkosten separat.",
    summaries: {
      web: "Unternehmenswebsites von der Domain bis zum Go-live – mit optionaler technischer Wartung und Inhaltspflege.",
      workplace: "Microsoft 365, Entra ID und Intune einrichten und betreuen: Benutzer, Geräte und Unternehmens-Apps im vereinbarten Umfang.",
      cloud: "Linux-Server und Docker-Anwendungen pflegen, Sicherungen prüfen und Wiederherstellung stichprobenartig testen.",
      individual: "Individualsoftware, Schnittstellen, Automatisierung und Shopify-Shops: Entwicklung und Pflege nach Ihrem Bedarf.",
    },
  },
  en: {
    home: "Home", services: "Services", details: "Explore this service", overview: "View all services",
    eyebrow: "IT services for SMEs · Munich and within 50 km",
    heading: "The right support for your next step.",
    intro: "A new website, digital workplaces, supported applications or a custom solution: find the right starting point here. Each service page explains what we deliver, how support works and which costs to plan for.",
    viewScope: "Explore the scope", configure: "Configure your package", pricing: "Services and prices",
    pricingTitle: "Start cleanly. Stay reliably supported afterwards.",
    pricingText: "Choose the option that fits. The focus is on the responsibility we take on and the operating state you want to maintain. One-off delivery and ongoing support remain clearly separated.",
    individualPricingTitle: "Your project defines the scope.",
    individualPricingText: "Do you need a new solution, help with an existing project or both? Select Individual Care and describe your project. One-off delivery and ongoing maintenance are agreed separately in the quote.",
    carePricingTitle: "A reliable operating framework for your application.",
    carePricingText: "Monthly support covers the operating scope described below. Setup, migration and existing issues are assessed separately before handover so responsibilities are clear during ongoing operations.",
    conditions: "Service terms & additional work", related: "Other ways to support your business",
    region: "Fürstenfeldbruck · Munich · within 50 km", regionalTitle: "One contact for delivery and ongoing support.",
    regionalText: "Leon Pllana IT-Solutions supports small and medium-sized businesses in the Munich area. Work can be delivered remotely; on-site appointments within the area are arranged as needed. Together, we agree which systems, tasks and goals the engagement covers.",
    overviewHelp: "Not sure which package fits?", overviewHelpText: "Describe your starting point. Together, we clarify which services and level of support make sense for your business.",
    contact: "Discuss your project", from: "from", monthly: "/ month", once: "one-off", setupOptional: "Optional setup", onRequest: "On request", net: "All prices are net; third-party costs are separate.",
    summaries: {
      web: "Company websites from domain registration to go-live, with optional technical maintenance and content updates.",
      workplace: "Microsoft 365, Entra ID and Intune setup and support: users, devices and business apps within the agreed scope.",
      cloud: "Maintain Linux servers and Docker applications, review backups and carry out sample restore tests.",
      individual: "Custom software, integrations, automation and Shopify shops: development and maintenance for your needs.",
    },
  },
  sq: {
    home: "Faqja kryesore", services: "Shërbimet", details: "Shërbimi në detaje", overview: "Shikoni të gjitha shërbimet",
    eyebrow: "Shërbime IT për NVM · Mynih dhe rrethina deri në 50 km",
    heading: "Mbështetja e duhur për hapin tuaj të ardhshëm.",
    intro: "Një faqe e re web, vende pune digjitale, aplikacione të mirëmbajtura ose zgjidhje individuale: këtu gjeni pikënisjen e duhur. Çdo faqe shërbimi shpjegon çfarë realizojmë, si funksionon mbështetja dhe cilat kosto duhet të planifikoni.",
    viewScope: "Shikoni shërbimet e përfshira", configure: "Përzgjidhni paketën", pricing: "Shërbimet dhe çmimet",
    pricingTitle: "Filloni pastër. Qëndroni të mbështetur në mënyrë të besueshme.",
    pricingText: "Zgjidhni variantin e përshtatshëm. Fokusi është te përgjegjësia që marrim përsipër dhe gjendja që duhet të ruhet në vazhdimësi. Realizimi njëherësh dhe mirëmbajtja periodike mbeten të ndara qartë.",
    individualPricingTitle: "Projekti juaj përcakton shërbimet.",
    individualPricingText: "Ju nevojitet një zgjidhje e re, ndihmë me një projekt ekzistues ose të dyja? Zgjidhni Individual Care dhe përshkruani projektin. Realizimi njëherësh dhe mirëmbajtja periodike dakordohen veçmas në ofertë.",
    carePricingTitle: "Një kornizë e besueshme funksionimi për aplikacionin tuaj.",
    carePricingText: "Mbështetja mujore mbulon fushën e përshkruar të funksionimit. Konfigurimi, migrimi dhe problemet ekzistuese sqarohen veçmas para dorëzimit, që përgjegjësitë në operim të jenë të qarta.",
    conditions: "Kushtet e shërbimit & punët shtesë", related: "Shërbime të tjera për biznesin tuaj",
    region: "Fürstenfeldbruck · Mynih · rrethina deri në 50 km", regionalTitle: "Një kontakt për realizimin dhe mirëmbajtjen.",
    regionalText: "Leon Pllana IT-Solutions mbështet ndërmarrjet e vogla dhe të mesme në rajonin e Mynihut. Bashkëpunimi mund të zhvillohet në distancë; takimet në vend dakordohen sipas nevojës. Së bashku përcaktojmë sistemet, detyrat dhe qëllimet e angazhimit.",
    overviewHelp: "Nuk jeni të sigurt cila paketë ju përshtatet?", overviewHelpText: "Përshkruani situatën tuaj. Së bashku sqarojmë shërbimet dhe nivelin e mbështetjes që ka kuptim për biznesin tuaj.",
    contact: "Diskutoni projektin", from: "nga", monthly: "/ muaj", once: "një herë", setupOptional: "Fillim opsional", onRequest: "Me kërkesë", net: "Të gjitha çmimet neto; kostot e palëve të treta veçmas.",
    summaries: {
      web: "Faqe biznesi nga regjistrimi i domenit deri te publikimi, me mirëmbajtje teknike dhe përditësim përmbajtjeje opsional.",
      workplace: "Konfigurim dhe mirëmbajtje e Microsoft 365, Entra ID dhe Intune: përdorues, pajisje dhe aplikacione sipas marrëveshjes.",
      cloud: "Mirëmbajtje serverësh Linux dhe aplikacionesh Docker, kontroll i kopjeve rezervë dhe teste rikthimi me mostra.",
      individual: "Softuer i personalizuar, integrime, automatizim dhe dyqane Shopify: zhvillim dhe mirëmbajtje sipas nevojave tuaja.",
    },
  },
} satisfies Record<Locale, object>;
