import type { Locale } from "@/lib/i18n";
import type { ServicePageCopy } from "./types";

export const webCareCopy = {
  de: {
    seoTitle: "Website erstellen lassen & warten in München | Web Care",
    seoDescription: "Websites für Unternehmen in München und Umgebung: von Domain und Gestaltung bis Go-live. Mit optionaler laufender Wartung und Inhaltspflege durch Web Care.",
    eyebrow: "Web Care · Websites für Unternehmen",
    heading: "Website-Erstellung und Wartung für Ihr Unternehmen.",
    intro: "Ihre Website soll erklären, was Sie leisten, Vertrauen schaffen und den Weg zur Anfrage erleichtern. Leon Pllana IT-Solutions aus Fürstenfeldbruck begleitet Unternehmen in München und 50 km Umland von der ersten Struktur bis zur Veröffentlichung – auf Wunsch mit anschließender Betreuung.",
    problemsTitle: "Kommt Ihnen das bekannt vor?",
    problems: [
      "Ihre Leistungen haben sich weiterentwickelt, auf der Website stehen noch alte Informationen.",
      "Für Updates, Sicherungen und kleine Änderungen fehlt im Tagesgeschäft ein fester Verantwortlicher.",
      "Sie möchten eine Website erstellen lassen und brauchen Klarheit über Ablauf, Zuständigkeiten und Kosten.",
    ],
    benefitsTitle: "Ein Unternehmensauftritt mit klarem Zweck",
    benefits: [
      { title: "Ihr Angebot wird greifbar", text: "Gemeinsam ordnen wir Leistungen, Inhalte und Kontaktwege. Besucher sollen schnell erkennen, ob Ihr Unternehmen zu ihrem Anliegen passt." },
      { title: "Ein Ansprechpartner für die Umsetzung", text: "Domainregistrierung, technische Anbindung und Website-Erstellung werden als zusammenhängendes Projekt geplant. Sie wissen, welche Inhalte und Freigaben gebraucht werden." },
      { title: "Pflege lässt sich einplanen", text: "Mit Web Care erhalten regelmäßige technische Aufgaben und kleine Inhaltsänderungen einen festen Rahmen. Erledigte Arbeiten werden kurz dokumentiert." },
    ],
    deliverablesTitle: "Was Sie konkret erhalten",
    deliverables: [
      { title: "Struktur und Gestaltung", text: "Wir stimmen Seitenaufbau, Darstellung und die vereinbarten Inhalte ab. Die Umsetzung berücksichtigt Smartphones und Desktop-Geräte; Seiten, Funktionen und Korrekturrunden stehen vor Beginn fest." },
      { title: "Von der Domain bis zum Go-live", text: "Die Erstellung umfasst Domainregistrierung, DNS- und Hosting-Anbindung, die vereinbarten Seiten, Funktionstests und die Übergabe. Laufende Domain- und Hostinggebühren werden separat ausgewiesen." },
      { title: "Regelmäßige technische Pflege", text: "Die Betreuung umfasst eine vereinbarte Website beziehungsweise CMS-Installation mit monatlicher Pflege, vereinbarten Updates und Funktionstests. Bei eingerichtetem Website-Backup prüfen wir wöchentlich die Sicherungsergebnisse." },
      { title: "Kleine Änderungen an Ihren Inhalten", text: "Bereitgestellte Texte und Bilder können im laufenden Betreuungsrahmen eingepflegt werden. Regelmäßige Pflege hat Vorrang; zusätzliche größere Änderungen stimmen wir transparent mit Ihnen ab." },
    ],
    processTitle: "So wird aus Ihrer Anfrage eine betreute Website",
    process: [
      { title: "Ziel und Bestand klären", text: "Wir besprechen Ihr Angebot, die gewünschten Seiten und vorhandene Zugänge. Bei einer bestehenden Website prüfen wir zunächst Zustand und Übernahmefähigkeit." },
      { title: "Umfang vereinbaren und umsetzen", text: "Sie erhalten ein Angebot mit Leistungen, benötigten Inhalten und Fremdkosten. Nach der Umsetzung prüfen wir die vereinbarten Funktionen und stimmen die Veröffentlichung ab." },
      { title: "Übergeben und bei Bedarf weiterpflegen", text: "Nach der Übergabe können Sie die laufende Betreuung starten. Servicefenster und Zusammenarbeit werden vereinbart; zusätzlichen Aufwand stimmen wir vorab ab." },
    ],
    faqTitle: "Häufige Fragen zu Website-Erstellung und Web Care",
    faqs: [
      { question: "Kann ich Erstellung und Betreuung getrennt anfragen?", answer: "Ja. Sie können nur die Website-Erstellung, nur Web Care für eine geeignete bestehende Website oder beides zusammen auswählen. Eine laufende Betreuung ist keine Voraussetzung für die Erstellung." },
      { question: "Welche Inhalte muss ich liefern?", answer: "Wir vereinbaren vor Projektbeginn, welche Texte, Bilder, Logos und weiteren Inhalte Sie bereitstellen. Texterstellung, zusätzliche Seiten und größere Designänderungen werden bei Bedarf gesondert angeboten." },
      { question: "Ist ein Website-Backup automatisch eingerichtet?", answer: "Die wöchentliche Prüfung gilt für eine bereits eingerichtete Sicherung. Falls diese fehlt oder angepasst werden muss, vereinbaren wir die Backup-Einrichtung vor Betreuungsbeginn separat." },
      { question: "Was passiert bei zusätzlichen oder größeren Änderungen?", answer: "Die vereinbarte Routinepflege hat Vorrang. Wenn darüber hinaus größere Änderungen oder zusätzliche Arbeiten sinnvoll sind, stimmen wir Umfang und Kosten vorab mit Ihnen ab. Eine 24/7-Betreuung ist nicht enthalten." },
      { question: "Passt Web Care auch für einen Shopify-Shop?", answer: "Shops und individuelle Webanwendungen werden unter Individual Care angefragt. Dort lassen sich Erstellung, Funktionen und laufende Pflege passend zu Ihrem konkreten Vorhaben vereinbaren." },
    ],
    ctaTitle: "Was soll Ihre Website als Nächstes leisten?",
    ctaText: "Wählen Sie Erstellung, Betreuung oder die Kombination. Im Kontaktformular sehen Sie Ihre Auswahl mit getrennten Einmal- und Monatskosten und können Ihr Vorhaben unverbindlich beschreiben.",
  },
  en: {
    seoTitle: "Website design & maintenance in Munich | Web Care",
    seoDescription: "Company websites in Munich and the surrounding area: from domain and design to go-live. Add ongoing maintenance and content updates with Web Care.",
    eyebrow: "Web Care · Company websites",
    heading: "Website creation and maintenance for your business.",
    intro: "Your website should explain what you do, build trust and make it easy to enquire. Based in Fürstenfeldbruck, Leon Pllana IT-Solutions supports companies in Munich and within 50 km, from the initial structure to launch – with ongoing support if you need it.",
    problemsTitle: "Does this sound familiar?",
    problems: [
      "Your services have evolved, but your website still shows outdated information.",
      "Day-to-day work leaves nobody clearly responsible for updates, backups and minor changes.",
      "You want a new website and need clarity on the process, responsibilities and costs.",
    ],
    benefitsTitle: "A company website with a clear purpose",
    benefits: [
      { title: "Make your services easy to understand", text: "Together, we organise your services, content and contact options. Visitors should quickly see whether your company can help with their needs." },
      { title: "One contact for implementation", text: "Domain registration, technical connections and website creation are planned as one project. You know which content and approvals are needed." },
      { title: "Give maintenance a regular place", text: "Web Care provides a defined scope for recurring technical tasks and minor content changes. Completed work is briefly documented." },
    ],
    deliverablesTitle: "What you receive",
    deliverables: [
      { title: "Structure and design", text: "We agree the page structure, presentation and content. The website is built for smartphones and desktop devices; pages, features and revision rounds are defined before work begins." },
      { title: "From domain to go-live", text: "Website creation includes domain registration, DNS and hosting connections, the agreed pages, functional testing and handover. Recurring domain and hosting fees are listed separately." },
      { title: "Regular technical maintenance", text: "Support covers one agreed website or CMS installation, with monthly maintenance, agreed updates and functional checks. Where website backups are configured, we review the results weekly." },
      { title: "Minor content changes", text: "Supplied text and images can be added within the ongoing support scope. Regular maintenance takes priority; larger additional changes are agreed transparently with you in advance." },
    ],
    processTitle: "From your enquiry to a maintained website",
    process: [
      { title: "Clarify goals and review the existing site", text: "We discuss your services, required pages and existing access. For an existing website, we first review its condition and suitability for ongoing support." },
      { title: "Agree the scope and build", text: "You receive a quote covering the work, required content and third-party costs. After implementation, we check the agreed functions and coordinate publication." },
      { title: "Hand over and maintain if needed", text: "You can start ongoing support after handover. Service windows and working arrangements are agreed; additional work is discussed in advance." },
    ],
    faqTitle: "Questions about website creation and Web Care",
    faqs: [
      { question: "Can I request creation and maintenance separately?", answer: "Yes. You can select website creation alone, Web Care for a suitable existing website, or both together. Ongoing support is not a requirement for website creation." },
      { question: "Which content do I need to supply?", answer: "Before work starts, we agree which text, images, logos and other content you will provide. Copywriting, additional pages and major design changes are quoted separately when needed." },
      { question: "Is a website backup set up automatically?", answer: "The weekly review applies to an existing backup configuration. If backups are missing or need changes, we agree the setup separately before support begins." },
      { question: "What happens with larger or additional changes?", answer: "Agreed routine maintenance takes priority. If larger changes or additional work are useful, we agree the scope and cost with you in advance. 24/7 support is not included." },
      { question: "Does Web Care also cover a Shopify shop?", answer: "Shops and custom web applications are handled through Individual Care. Creation, features and ongoing maintenance can then be agreed around your specific project." },
    ],
    ctaTitle: "What should your website do next?",
    ctaText: "Choose creation, ongoing support or both. The contact form shows your selection with separate one-off and monthly costs, ready for your non-binding project enquiry.",
  },
  sq: {
    seoTitle: "Krijim dhe mirëmbajtje faqesh në Mynih | Web Care",
    seoDescription: "Faqe biznesi në Mynih dhe rrethina: nga domeni dhe dizajni deri te publikimi. Me mirëmbajtje të vazhdueshme dhe përditësim përmbajtjeje përmes Web Care.",
    eyebrow: "Web Care · Faqe për biznese",
    heading: "Krijim dhe mirëmbajtje faqesh web për biznesin tuaj.",
    intro: "Faqja juaj duhet të shpjegojë çfarë ofroni, të krijojë besim dhe ta bëjë të lehtë dërgimin e një kërkese. Leon Pllana IT-Solutions nga Fürstenfeldbruck mbështet bizneset në Mynih dhe 50 km përreth, nga struktura fillestare deri te publikimi – me mirëmbajtje të mëtejshme sipas dëshirës.",
    problemsTitle: "A ju tingëllojnë të njohura këto situata?",
    problems: [
      "Shërbimet tuaja kanë evoluar, por faqja ende paraqet informacione të vjetra.",
      "Në punën e përditshme mungon një përgjegjës i caktuar për përditësimet, backup-et dhe ndryshimet e vogla.",
      "Dëshironi një faqe të re dhe ju duhet qartësi për procesin, përgjegjësitë dhe kostot.",
    ],
    benefitsTitle: "Një faqe kompanie me qëllim të qartë",
    benefits: [
      { title: "Oferta juaj bëhet e kuptueshme", text: "Së bashku organizojmë shërbimet, përmbajtjen dhe mënyrat e kontaktit. Vizitorët duhet të kuptojnë shpejt nëse kompania juaj i përgjigjet nevojës së tyre." },
      { title: "Një person kontakti për realizimin", text: "Regjistrimi i domenit, lidhjet teknike dhe krijimi i faqes planifikohen si një projekt i përbashkët. Ju dini çfarë përmbajtjeje dhe miratimesh nevojiten." },
      { title: "Mirëmbajtje e planifikueshme", text: "Web Care përcakton një fushë të qartë për detyrat teknike periodike dhe ndryshimet e vogla të përmbajtjes. Punët e përfunduara dokumentohen shkurtimisht." },
    ],
    deliverablesTitle: "Çfarë merrni konkretisht",
    deliverables: [
      { title: "Strukturë dhe dizajn", text: "Dakordojmë strukturën e faqeve, paraqitjen dhe përmbajtjen. Realizimi merr parasysh telefonat dhe kompjuterët; faqet, funksionet dhe raundet e korrigjimeve përcaktohen para fillimit." },
      { title: "Nga domeni deri te publikimi", text: "Krijimi përfshin regjistrimin e domenit, lidhjen me DNS dhe hostimin, faqet e dakorduara, testimin e funksioneve dhe dorëzimin. Tarifat periodike të domenit dhe hostimit paraqiten veçmas." },
      { title: "Mirëmbajtje teknike e rregullt", text: "Mbështetja mbulon një faqe ose instalim CMS të dakorduar, me mirëmbajtje mujore, përditësime të dakorduara dhe kontrolle funksionale. Kur backup-i është konfiguruar, rezultatet kontrollohen çdo javë." },
      { title: "Ndryshime të vogla të përmbajtjes", text: "Tekstet dhe imazhet e ofruara mund të vendosen brenda mirëmbajtjes së vazhdueshme. Mirëmbajtja e rregullt ka përparësi; ndryshimet më të mëdha dakordohen paraprakisht." },
    ],
    processTitle: "Nga kërkesa juaj te një faqe e mirëmbajtur",
    process: [
      { title: "Sqarimi i qëllimit dhe gjendjes aktuale", text: "Diskutojmë shërbimet tuaja, faqet e dëshiruara dhe qasjet ekzistuese. Për një faqe ekzistuese, fillimisht kontrollojmë gjendjen dhe përshtatshmërinë për mbështetje." },
      { title: "Dakordimi i fushës dhe realizimi", text: "Merrni një ofertë me shërbimet, përmbajtjen e nevojshme dhe kostot e palëve të treta. Pas realizimit kontrollojmë funksionet e dakorduara dhe koordinojmë publikimin." },
      { title: "Dorëzimi dhe mirëmbajtja sipas nevojës", text: "Pas dorëzimit mund të filloni mbështetjen e vazhdueshme. Oraret e shërbimit dhe bashkëpunimi dakordohen; puna shtesë diskutohet paraprakisht." },
    ],
    faqTitle: "Pyetje për krijimin e faqes dhe Web Care",
    faqs: [
      { question: "A mund t'i kërkoj krijimin dhe mirëmbajtjen veçmas?", answer: "Po. Mund të zgjidhni vetëm krijimin e faqes, vetëm Web Care për një faqe ekzistuese të përshtatshme ose të dyja bashkë. Mbështetja e vazhdueshme nuk është kusht për krijimin e faqes." },
      { question: "Çfarë përmbajtjeje duhet të ofroj?", answer: "Para fillimit dakordojmë cilat tekste, imazhe, logo dhe përmbajtje të tjera do të ofroni. Shkrimi i teksteve, faqet shtesë dhe ndryshimet e mëdha të dizajnit ofertohen veçmas sipas nevojës." },
      { question: "A konfigurohet automatikisht backup-i i faqes?", answer: "Kontrolli javor vlen për një backup tashmë të konfiguruar. Nëse mungon ose kërkon ndryshime, konfigurimin e dakordojmë veçmas para fillimit të mbështetjes." },
      { question: "Çfarë ndodh nëse koha e përfshirë nuk mjafton?", answer: "Mirëmbajtja rutinë ka përparësi brenda kohës së përbashkët. Punët shtesë të parashikueshme diskutohen paraprakisht dhe faturohen veçmas pas miratimit. Koha e papërdorur nuk bartet në muajin tjetër; mbështetja 24/7 nuk përfshihet." },
      { question: "A mbulon Web Care edhe një dyqan Shopify?", answer: "Dyqanet dhe aplikacionet e personalizuara në internet kërkohen përmes Individual Care. Krijimi, funksionet dhe mirëmbajtja e vazhdueshme përcaktohen sipas projektit tuaj konkret." },
    ],
    ctaTitle: "Çfarë duhet të arrijë më tej faqja juaj?",
    ctaText: "Zgjidhni krijimin, mbështetjen ose kombinimin. Formulari i kontaktit paraqet përzgjedhjen tuaj me kosto të ndara njëherëshe dhe mujore, ku mund ta përshkruani projektin pa detyrim.",
  },
} satisfies Record<Locale, ServicePageCopy>;
