import type { Locale } from "@/lib/i18n";
import type { ServicePageCopy } from "./types";

export const workplaceCareCopy = {
  de: {
    seoTitle: "Microsoft 365 & Intune einrichten in München | Workplace Care",
    seoDescription: "Microsoft 365, Entra ID und Intune für Unternehmen in München und Umgebung einrichten und betreuen lassen. Klare Einrichtungskosten, optionale laufende Betreuung.",
    eyebrow: "Workplace Care · Microsoft 365 und Intune",
    heading: "Microsoft 365 und Intune für Ihre digitalen Arbeitsplätze.",
    intro: "Benutzerkonten, Zugriffsregeln und Geräteverwaltung gehören zusammen. Leon Pllana IT-Solutions aus Fürstenfeldbruck unterstützt Unternehmen in München und 50 km Umland beim Aufbau ihrer Microsoft-365-Umgebung und bei der anschließenden Pflege. Umfang und Zuständigkeiten werden passend zu Ihrem Betrieb vereinbart.",
    problemsTitle: "Wo die Verwaltung im Alltag hängen bleibt",
    problems: [
      "Benutzerkonten und Geräte werden einzeln eingerichtet; gemeinsame Vorgaben sind kaum dokumentiert.",
      "Bei Eintritten, Gerätewechseln oder Änderungen ist unklar, wer welche Einstellungen prüft.",
      "Sie möchten Microsoft 365 und Intune einführen, können Einrichtungsaufwand, Lizenzen und laufende Betreuung aber noch nicht auseinanderhalten.",
    ],
    benefitsTitle: "Eine nachvollziehbare Grundlage für Ihre Arbeitsplätze",
    benefits: [
      { title: "Gemeinsame Regeln für Benutzer und Geräte", text: "Die vereinbarte Entra-ID- und Intune-Konfiguration schafft eine Grundlage für Konten, Zugriffe und Geräteverwaltung. Einstellungen werden mit Ihrem tatsächlichen Arbeitsablauf abgestimmt." },
      { title: "Veränderungen bleiben nachvollziehbar", text: "Regelmäßige Prüfungen und dokumentierte Anpassungen helfen, Auffälligkeiten einzuordnen. Für vereinbarte Standardaufgaben gibt es einen festen Ansprechpartner." },
      { title: "Kosten lassen sich zuordnen", text: "Einrichtung, laufende Betreuung und Microsoft-Lizenzen werden getrennt betrachtet. Sie sehen, was das Projekt umfasst und welcher Pflegeaufwand regelmäßig eingeplant ist." },
    ],
    deliverablesTitle: "Von der Einrichtung bis zur laufenden Betreuung",
    deliverables: [
      { title: "Microsoft-365-Tenant und Benutzerkonten", text: "Für einen neuen Unternehmensmandanten werden die vereinbarten Benutzer angelegt. Benutzerzahl, Gerätezahl, benötigte Lizenzen und konkrete Konfiguration klären wir vor Projektbeginn." },
      { title: "Entra ID und Intune als Grundlage", text: "Die Einrichtung umfasst die Entra-ID-Grundstruktur, grundlegende Zugriffsrichtlinien und Intune-Geräteverwaltung. Vereinbarte Geräte- und Richtlinienkonfigurationen werden getestet und dokumentiert übergeben." },
      { title: "Monatliche Zustandsprüfung", text: "Workplace Care umfasst im Referenzumfang einen bestehenden Tenant, bis zu 10 Benutzer und 15 bereits in Intune eingebundene Geräte. Geprüft werden Microsoft 365, Intune, vereinbarte Unternehmens-Apps, Geräte-Compliance und grundlegende Zugriffsrichtlinien." },
      { title: "Kleine Anpassungen im laufenden Betrieb", text: "Benutzer-, Geräte- und Standard-App-Anpassungen können im laufenden Betreuungsrahmen übernommen werden. Regelmäßige Zustandsprüfungen und Betriebssicherheit haben Vorrang; größere Vorhaben stimmen wir separat ab." },
    ],
    processTitle: "So starten wir mit Ihrer Umgebung",
    process: [
      { title: "Arbeitsweise und Bestand aufnehmen", text: "Wir klären Benutzer, Geräte, Anwendungen und vorhandene Zugänge. Bestehende Systeme werden auf Übernahmefähigkeit geprüft; Migrationsbedarf wird separat erfasst." },
      { title: "Konfiguration vereinbaren und testen", text: "Das Angebot hält Einrichtungsumfang und Lizenzbedarf fest. Anschließend werden die vereinbarten Konten, Richtlinien und Geräteeinstellungen umgesetzt und auf ihre Funktion geprüft." },
      { title: "Übergeben und Betreuung abstimmen", text: "Sie erhalten eine dokumentierte Übergabe. Wenn Sie Workplace Care wählen, vereinbaren wir Servicefenster, Zuständigkeiten und den Umgang mit zusätzlichen Aufgaben." },
    ],
    faqTitle: "Häufige Fragen zu Microsoft 365 und Workplace Care",
    faqs: [
      { question: "Ist die Einrichtung auch ohne Wartungsvertrag möglich?", answer: "Ja. Microsoft-365-Einrichtung und Workplace Care sind einzeln oder zusammen anfragbar. Für eine bestehende geeignete Umgebung können Sie auch ausschließlich die laufende Betreuung wählen." },
      { question: "Sind zehn Benutzer und fünfzehn Geräte auch bei der Einrichtung enthalten?", answer: "Diese Zahlen beschreiben den Referenzumfang der monatlichen Betreuung. Benutzer- und Gerätezahl sowie die konkrete Konfiguration des Einrichtungsprojekts werden separat vorab vereinbart." },
      { question: "Sind Microsoft-Lizenzen und Datenmigrationen enthalten?", answer: "Microsoft-Lizenzen sind nicht im Einrichtungs- oder Betreuungspreis enthalten. Datenmigrationen, besondere App-Paketierungen und umfangreiche Richtlinienänderungen werden gesondert angeboten. Den benötigten Umfang klären wir vor Beginn." },
      { question: "Gehört eine zusätzliche Microsoft-365-Datensicherung dazu?", answer: "Ein zusätzliches Backup für Microsoft 365 ist kein Bestandteil von Workplace Care. Wenn Sie eine solche Sicherung benötigen, vereinbaren wir Einrichtung, Speicher und laufende Betreuung separat." },
      { question: "Wie werden Support und zusätzlicher Aufwand organisiert?", answer: "Routinepflege und die vereinbarten Standardaufgaben haben Vorrang. Zusätzliche oder größere Vorhaben stimmen wir vorab mit Ihnen ab und bieten sie bei Bedarf separat an. Servicefenster und Reaktionszeiten stehen im Angebot; eine Rufbereitschaft oder 24/7-Betreuung ist nicht enthalten." },
    ],
    ctaTitle: "Wie sollen Ihre digitalen Arbeitsplätze aufgestellt sein?",
    ctaText: "Wählen Sie Einrichtung, Betreuung oder beides. Nennen Sie im Kontaktformular gern Ihre Benutzer- und Gerätezahl sowie vorhandene Systeme. Daraus entsteht ein Angebot mit klar abgegrenzten Leistungen.",
  },
  en: {
    seoTitle: "Microsoft 365 & Intune setup in Munich | Workplace Care",
    seoDescription: "Microsoft 365, Entra ID and Intune setup and support for companies in Munich and the surrounding area. Clear setup costs with optional ongoing support.",
    eyebrow: "Workplace Care · Microsoft 365 and Intune",
    heading: "Microsoft 365 and Intune for your digital workplaces.",
    intro: "User accounts, access policies and device management belong together. Based in Fürstenfeldbruck, Leon Pllana IT-Solutions helps companies in Munich and within 50 km establish and maintain their Microsoft 365 environment. Scope and responsibilities are agreed around your business.",
    problemsTitle: "Where everyday administration gets stuck",
    problems: [
      "User accounts and devices are set up individually, with little documentation of shared policies.",
      "When employees join, devices change or settings need updating, it is unclear who checks what.",
      "You want to introduce Microsoft 365 and Intune but need to separate setup work, licences and ongoing support.",
    ],
    benefitsTitle: "A clear foundation for your workplaces",
    benefits: [
      { title: "Shared rules for users and devices", text: "The agreed Entra ID and Intune configuration provides a foundation for accounts, access and device management. Settings are aligned with how your team actually works." },
      { title: "Keep track of changes", text: "Regular reviews and documented adjustments help you understand findings. A dedicated contact handles the agreed standard tasks." },
      { title: "Understand each part of the cost", text: "Setup, ongoing support and Microsoft licences are considered separately. You can see what the project includes and how much recurring maintenance is planned." },
    ],
    deliverablesTitle: "From initial setup to ongoing support",
    deliverables: [
      { title: "Microsoft 365 tenant and user accounts", text: "The agreed users are created in a new company tenant. We clarify user and device counts, required licences and the specific configuration before the project starts." },
      { title: "Entra ID and Intune foundations", text: "Setup includes the Entra ID foundation, basic access policies and Intune device management. Agreed device and policy configurations are tested and handed over with documentation." },
      { title: "Monthly health review", text: "Workplace Care has a reference scope of one existing tenant, up to 10 users and 15 devices already enrolled in Intune. Reviews cover Microsoft 365, Intune, agreed business apps, device compliance and basic access policies." },
      { title: "Minor adjustments during operation", text: "User, device and standard app changes can be handled within the ongoing support scope. Regular health reviews and operational reliability take priority; larger projects are agreed separately." },
    ],
    processTitle: "How we get started with your environment",
    process: [
      { title: "Review your workflow and existing systems", text: "We clarify users, devices, applications and available access. Existing systems are assessed for ongoing support; any migration requirements are recorded separately." },
      { title: "Agree and test the configuration", text: "The quote specifies the setup scope and required licences. The agreed accounts, policies and device settings are then implemented and functionally checked." },
      { title: "Hand over and agree ongoing support", text: "You receive a documented handover. If you choose Workplace Care, we agree service windows, responsibilities and how additional tasks are handled." },
    ],
    faqTitle: "Questions about Microsoft 365 and Workplace Care",
    faqs: [
      { question: "Can I request setup without a maintenance contract?", answer: "Yes. Microsoft 365 setup and Workplace Care are available separately or together. You can also choose ongoing support alone for a suitable existing environment." },
      { question: "Does setup also include ten users and fifteen devices?", answer: "Those numbers describe the reference scope of monthly support. User and device counts and the specific configuration for the setup project are agreed separately in advance." },
      { question: "Are Microsoft licences and data migrations included?", answer: "Microsoft licences are excluded from both setup and support prices. Data migrations, specialist app packaging and extensive policy changes are quoted separately. We clarify the required scope before work begins." },
      { question: "Is an additional Microsoft 365 backup included?", answer: "An additional Microsoft 365 backup is not part of Workplace Care. If you need one, setup, storage and ongoing support are agreed separately." },
      { question: "How are support and additional work organised?", answer: "Routine maintenance and the agreed standard tasks take priority. Additional or larger projects are agreed with you in advance and quoted separately where needed. Service windows and response times are specified in the quote; on-call or 24/7 support is not included." },
    ],
    ctaTitle: "How should your digital workplaces be organised?",
    ctaText: "Choose setup, ongoing support or both. Include your user and device counts and existing systems in the contact form if available. We use these details to prepare a quote with a clearly defined scope.",
  },
  sq: {
    seoTitle: "Konfigurim Microsoft 365 & Intune në Mynih | Workplace Care",
    seoDescription: "Konfigurim dhe mbështetje për Microsoft 365, Entra ID dhe Intune për bizneset në Mynih dhe rrethina. Kosto të qarta konfigurimi dhe mbështetje sipas dëshirës.",
    eyebrow: "Workplace Care · Microsoft 365 dhe Intune",
    heading: "Microsoft 365 dhe Intune për vendet tuaja digjitale të punës.",
    intro: "Llogaritë e përdoruesve, rregullat e qasjes dhe administrimi i pajisjeve duhen menduar së bashku. Leon Pllana IT-Solutions nga Fürstenfeldbruck ndihmon bizneset në Mynih dhe 50 km përreth të krijojnë dhe mirëmbajnë mjedisin e tyre Microsoft 365. Fusha dhe përgjegjësitë përcaktohen sipas biznesit tuaj.",
    problemsTitle: "Ku ngec administrimi i përditshëm",
    problems: [
      "Llogaritë dhe pajisjet konfigurohen një nga një; rregullat e përbashkëta dokumentohen pak.",
      "Kur vijnë punonjës të rinj, ndërrohen pajisje ose kërkohen ndryshime, nuk dihet qartë kush kontrollon cilat konfigurime.",
      "Dëshironi të përdorni Microsoft 365 dhe Intune, por ju duhet të ndani punën e konfigurimit, licencat dhe mbështetjen e vazhdueshme.",
    ],
    benefitsTitle: "Një bazë e kuptueshme për vendet tuaja të punës",
    benefits: [
      { title: "Rregulla të përbashkëta për përdoruesit dhe pajisjet", text: "Konfigurimi i dakorduar i Entra ID dhe Intune krijon një bazë për llogaritë, qasjet dhe administrimin e pajisjeve. Parametrat përshtaten me mënyrën reale të punës së ekipit tuaj." },
      { title: "Ndryshime të gjurmueshme", text: "Kontrollet e rregullta dhe ndryshimet e dokumentuara ndihmojnë për të kuptuar gjetjet. Për detyrat standarde të dakorduara keni një person kontakti." },
      { title: "Kosto që mund të dallohen qartë", text: "Konfigurimi, mbështetja e vazhdueshme dhe licencat Microsoft trajtohen veçmas. Shihni çfarë përfshin projekti dhe çfarë mirëmbajtjeje është planifikuar rregullisht." },
    ],
    deliverablesTitle: "Nga konfigurimi fillestar te mbështetja e vazhdueshme",
    deliverables: [
      { title: "Tenant Microsoft 365 dhe llogari përdoruesish", text: "Përdoruesit e dakorduar krijohen në një tenant të ri të kompanisë. Numrin e përdoruesve dhe pajisjeve, licencat e nevojshme dhe konfigurimin konkret i sqarojmë para fillimit të projektit." },
      { title: "Bazat e Entra ID dhe Intune", text: "Konfigurimi përfshin strukturën bazë të Entra ID, politikat bazë të qasjes dhe administrimin e pajisjeve me Intune. Konfigurimet e dakorduara të pajisjeve dhe politikave testohen dhe dorëzohen me dokumentim." },
      { title: "Kontroll mujor i gjendjes", text: "Fusha referuese e Workplace Care përfshin një tenant ekzistues, deri në 10 përdorues dhe 15 pajisje të regjistruara tashmë në Intune. Kontrollohen Microsoft 365, Intune, aplikacionet e dakorduara, përputhshmëria e pajisjeve dhe politikat bazë të qasjes." },
      { title: "Ndryshime të vogla gjatë përdorimit", text: "Ndryshimet e përdoruesve, pajisjeve dhe aplikacioneve standarde mund të realizohen brenda mirëmbajtjes së vazhdueshme. Kontrollet e rregullta dhe funksionimi i sigurt kanë përparësi; projektet më të mëdha dakordohen veçmas." },
    ],
    processTitle: "Si fillojmë me mjedisin tuaj",
    process: [
      { title: "Njohja e punës dhe sistemeve ekzistuese", text: "Sqarojmë përdoruesit, pajisjet, aplikacionet dhe qasjet në dispozicion. Sistemet ekzistuese vlerësohen për mbështetje; nevojat për migrim regjistrohen veçmas." },
      { title: "Dakordimi dhe testimi i konfigurimit", text: "Oferta përcakton fushën e konfigurimit dhe licencat e nevojshme. Më pas realizohen llogaritë, politikat dhe parametrat e pajisjeve të dakorduara dhe kontrollohet funksionimi." },
      { title: "Dorëzimi dhe dakordimi i mbështetjes", text: "Merrni një dorëzim të dokumentuar. Nëse zgjidhni Workplace Care, dakordojmë oraret e shërbimit, përgjegjësitë dhe trajtimin e detyrave shtesë." },
    ],
    faqTitle: "Pyetje për Microsoft 365 dhe Workplace Care",
    faqs: [
      { question: "A mund ta kërkoj konfigurimin pa kontratë mirëmbajtjeje?", answer: "Po. Konfigurimi i Microsoft 365 dhe Workplace Care mund të kërkohen veçmas ose së bashku. Për një mjedis ekzistues të përshtatshëm mund të zgjidhni edhe vetëm mbështetjen e vazhdueshme." },
      { question: "A përfshin edhe konfigurimi dhjetë përdorues dhe pesëmbëdhjetë pajisje?", answer: "Këto shifra përshkruajnë fushën referuese të mbështetjes mujore. Numri i përdoruesve dhe pajisjeve dhe konfigurimi konkret i projektit fillestar dakordohen veçmas paraprakisht." },
      { question: "A përfshihen licencat Microsoft dhe migrimi i të dhënave?", answer: "Licencat Microsoft nuk përfshihen në çmimin e konfigurimit apo mbështetjes. Migrimet e të dhënave, paketimi i veçantë i aplikacioneve dhe ndryshimet e mëdha të politikave ofertohen veçmas. Fushën e nevojshme e sqarojmë para fillimit." },
      { question: "A përfshihet një backup shtesë për Microsoft 365?", answer: "Backup-i shtesë për Microsoft 365 nuk është pjesë e Workplace Care. Nëse ju nevojitet, konfigurimi, hapësira e ruajtjes dhe mbështetja e vazhdueshme dakordohen veçmas." },
      { question: "Si organizohen mbështetja dhe puna shtesë?", answer: "Mirëmbajtja rutinë dhe detyrat standarde të dakorduara kanë përparësi. Projektet shtesë ose më të mëdha dakordohen paraprakisht dhe ofertohen veçmas sipas nevojës. Oraret e shërbimit dhe koha e reagimit përcaktohen në ofertë; mbështetja 24/7 nuk përfshihet." },
    ],
    ctaTitle: "Si dëshironi të organizohen vendet tuaja digjitale të punës?",
    ctaText: "Zgjidhni konfigurimin, mbështetjen ose të dyja. Në formular mund të shënoni numrin e përdoruesve dhe pajisjeve dhe sistemet ekzistuese. Mbi këtë bazë përgatisim një ofertë me shërbime të përcaktuara qartë.",
  },
} satisfies Record<Locale, ServicePageCopy>;
